// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myip_v1_0_HLS_myip_v1_0_HLS,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.135000,HLS_SYN_LAT=662,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=402,HLS_SYN_LUT=964,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module myip_v1_0_HLS (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_state7 = 8'd64;
parameter    ap_ST_fsm_state8 = 8'd128;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

 reg    ap_rst_n_inv;
reg   [6:0] mat_A_address0;
reg    mat_A_ce0;
reg    mat_A_we0;
wire   [31:0] mat_A_q0;
reg    mat_A_ce1;
wire   [31:0] mat_A_q1;
reg   [6:0] mat_A_1_address0;
reg    mat_A_1_ce0;
reg    mat_A_1_we0;
wire   [31:0] mat_A_1_q0;
reg    mat_A_1_ce1;
wire   [31:0] mat_A_1_q1;
reg   [6:0] mat_A_2_address0;
reg    mat_A_2_ce0;
reg    mat_A_2_we0;
wire   [31:0] mat_A_2_q0;
reg    mat_A_2_ce1;
wire   [31:0] mat_A_2_q1;
reg   [6:0] mat_A_3_address0;
reg    mat_A_3_ce0;
reg    mat_A_3_we0;
wire   [31:0] mat_A_3_q0;
reg    mat_A_3_ce1;
wire   [31:0] mat_A_3_q1;
reg   [5:0] mat_RES_address0;
reg    mat_RES_ce0;
reg    mat_RES_we0;
wire   [23:0] mat_RES_q0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_idle;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_ready;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_ce0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_we0;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_d0;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_ce0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_we0;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_d0;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_ce0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_we0;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_d0;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_ce0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_we0;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_d0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_S_AXIS_TREADY;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out_ap_vld;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out_ap_vld;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out_ap_vld;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out_ap_vld;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out_ap_vld;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out_ap_vld;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out_ap_vld;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out_ap_vld;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_idle;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_ready;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce0;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address1;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce1;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce0;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address1;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce1;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce0;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address1;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce1;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce0;
wire   [6:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address1;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce1;
wire   [5:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_ce0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_we0;
wire   [23:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_d0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_idle;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_ready;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TREADY;
wire   [5:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_address0;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_ce0;
wire   [31:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA;
wire    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID;
wire   [3:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP;
wire   [3:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB;
wire   [0:0] grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST;
reg    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
reg    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [31:0] M_AXIS_TDATA_reg;
reg   [3:0] M_AXIS_TKEEP_reg;
reg   [3:0] M_AXIS_TSTRB_reg;
reg   [0:0] M_AXIS_TLAST_reg;
reg   [7:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state8;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
reg   [31:0] M_AXIS_TDATA_int_regslice;
wire    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
reg   [3:0] M_AXIS_TKEEP_int_regslice;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
reg   [3:0] M_AXIS_TSTRB_int_regslice;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
reg   [0:0] M_AXIS_TLAST_int_regslice;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg = 1'b0;
#0 grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg = 1'b0;
end

myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
mat_A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_A_address0),
    .ce0(mat_A_ce0),
    .we0(mat_A_we0),
    .d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_d0),
    .q0(mat_A_q0),
    .address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address1),
    .ce1(mat_A_ce1),
    .q1(mat_A_q1)
);

myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
mat_A_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_A_1_address0),
    .ce0(mat_A_1_ce0),
    .we0(mat_A_1_we0),
    .d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_d0),
    .q0(mat_A_1_q0),
    .address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address1),
    .ce1(mat_A_1_ce1),
    .q1(mat_A_1_q1)
);

myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
mat_A_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_A_2_address0),
    .ce0(mat_A_2_ce0),
    .we0(mat_A_2_we0),
    .d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_d0),
    .q0(mat_A_2_q0),
    .address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address1),
    .ce1(mat_A_2_ce1),
    .q1(mat_A_2_q1)
);

myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
mat_A_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_A_3_address0),
    .ce0(mat_A_3_ce0),
    .we0(mat_A_3_we0),
    .d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_d0),
    .q0(mat_A_3_q0),
    .address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address1),
    .ce1(mat_A_3_ce1),
    .q1(mat_A_3_q1)
);

myip_v1_0_HLS_mat_RES_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_RES_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_RES_address0),
    .ce0(mat_RES_ce0),
    .we0(mat_RES_we0),
    .d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_d0),
    .q0(mat_RES_q0)
);

myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start),
    .ap_done(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done),
    .ap_idle(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_idle),
    .ap_ready(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID_int_regslice),
    .mat_A_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_address0),
    .mat_A_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_ce0),
    .mat_A_we0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_we0),
    .mat_A_d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_d0),
    .mat_A_1_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_address0),
    .mat_A_1_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_ce0),
    .mat_A_1_we0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_we0),
    .mat_A_1_d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_d0),
    .mat_A_2_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_address0),
    .mat_A_2_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_ce0),
    .mat_A_2_we0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_we0),
    .mat_A_2_d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_d0),
    .mat_A_3_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_address0),
    .mat_A_3_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_ce0),
    .mat_A_3_we0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_we0),
    .mat_A_3_d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA_int_regslice),
    .S_AXIS_TREADY(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP_int_regslice),
    .S_AXIS_TSTRB(S_AXIS_TSTRB_int_regslice),
    .S_AXIS_TLAST(S_AXIS_TLAST_int_regslice),
    .mat_B_7_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out),
    .mat_B_7_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out_ap_vld),
    .mat_B_6_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out),
    .mat_B_6_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out_ap_vld),
    .mat_B_5_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out),
    .mat_B_5_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out_ap_vld),
    .mat_B_4_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out),
    .mat_B_4_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out_ap_vld),
    .mat_B_3_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out),
    .mat_B_3_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out_ap_vld),
    .mat_B_2_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out),
    .mat_B_2_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out_ap_vld),
    .mat_B_1_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out),
    .mat_B_1_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out_ap_vld),
    .mat_B_out(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out),
    .mat_B_out_ap_vld(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out_ap_vld)
);

myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start),
    .ap_done(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done),
    .ap_idle(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_idle),
    .ap_ready(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_ready),
    .mat_A_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address0),
    .mat_A_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce0),
    .mat_A_q0(mat_A_q0),
    .mat_A_address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address1),
    .mat_A_ce1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce1),
    .mat_A_q1(mat_A_q1),
    .mat_A_1_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address0),
    .mat_A_1_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce0),
    .mat_A_1_q0(mat_A_1_q0),
    .mat_A_1_address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address1),
    .mat_A_1_ce1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce1),
    .mat_A_1_q1(mat_A_1_q1),
    .mat_A_2_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address0),
    .mat_A_2_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce0),
    .mat_A_2_q0(mat_A_2_q0),
    .mat_A_2_address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address1),
    .mat_A_2_ce1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce1),
    .mat_A_2_q1(mat_A_2_q1),
    .mat_A_3_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address0),
    .mat_A_3_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce0),
    .mat_A_3_q0(mat_A_3_q0),
    .mat_A_3_address1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address1),
    .mat_A_3_ce1(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce1),
    .mat_A_3_q1(mat_A_3_q1),
    .mat_B_1_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out),
    .mat_B_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out),
    .mat_B_2_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out),
    .mat_B_3_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out),
    .mat_B_4_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out),
    .mat_B_5_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out),
    .mat_B_6_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out),
    .mat_B_7_reload(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out),
    .mat_RES_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_address0),
    .mat_RES_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_ce0),
    .mat_RES_we0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_we0),
    .mat_RES_d0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_d0)
);

myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start),
    .ap_done(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done),
    .ap_idle(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_idle),
    .ap_ready(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_ready),
    .M_AXIS_TREADY(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TREADY),
    .mat_RES_address0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_address0),
    .mat_RES_ce0(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_ce0),
    .mat_RES_q0(mat_RES_q0),
    .M_AXIS_TDATA(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA),
    .M_AXIS_TVALID(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID),
    .M_AXIS_TKEEP(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP),
    .M_AXIS_TSTRB(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB),
    .M_AXIS_TLAST(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TDATA_int_regslice),
    .vld_in(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TKEEP_int_regslice),
    .vld_in(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TSTRB_int_regslice),
    .vld_in(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TLAST_int_regslice),
    .vld_in(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg <= 1'b1;
        end else if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_ready == 1'b1)) begin
            grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg <= 1'b1;
        end else if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_ready == 1'b1)) begin
            grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg <= 1'b1;
        end else if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_ready == 1'b1)) begin
            grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID == 1'b1))) begin
        M_AXIS_TDATA_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA;
        M_AXIS_TKEEP_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP;
        M_AXIS_TLAST_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST;
        M_AXIS_TSTRB_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID == 1'b1))) begin
        M_AXIS_TDATA_int_regslice = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA;
    end else begin
        M_AXIS_TDATA_int_regslice = M_AXIS_TDATA_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID == 1'b1))) begin
        M_AXIS_TKEEP_int_regslice = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP;
    end else begin
        M_AXIS_TKEEP_int_regslice = M_AXIS_TKEEP_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID == 1'b1))) begin
        M_AXIS_TLAST_int_regslice = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST;
    end else begin
        M_AXIS_TLAST_int_regslice = M_AXIS_TLAST_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID == 1'b1))) begin
        M_AXIS_TSTRB_int_regslice = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB;
    end else begin
        M_AXIS_TSTRB_int_regslice = M_AXIS_TSTRB_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        S_AXIS_TREADY_int_regslice = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_S_AXIS_TREADY;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_1_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_1_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_address0;
    end else begin
        mat_A_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_1_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_1_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_ce0;
    end else begin
        mat_A_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_1_ce1 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce1;
    end else begin
        mat_A_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_1_we0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_we0;
    end else begin
        mat_A_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_2_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_2_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_address0;
    end else begin
        mat_A_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_2_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_2_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_ce0;
    end else begin
        mat_A_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_2_ce1 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce1;
    end else begin
        mat_A_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_2_we0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_we0;
    end else begin
        mat_A_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_3_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_3_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_address0;
    end else begin
        mat_A_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_3_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_3_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_ce0;
    end else begin
        mat_A_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_3_ce1 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce1;
    end else begin
        mat_A_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_3_we0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_we0;
    end else begin
        mat_A_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_address0;
    end else begin
        mat_A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_ce0;
    end else begin
        mat_A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_A_ce1 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce1;
    end else begin
        mat_A_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mat_A_we0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_we0;
    end else begin
        mat_A_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mat_RES_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_RES_address0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_address0;
    end else begin
        mat_RES_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mat_RES_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_RES_ce0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_ce0;
    end else begin
        mat_RES_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mat_RES_we0 = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_we0;
    end else begin
        mat_RES_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign M_AXIS_TVALID_int_regslice = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID;

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg;

assign grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg;

assign grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TREADY = (ap_CS_fsm_state7 & M_AXIS_TREADY_int_regslice);

assign grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start = grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg;


reg find_kernel_block = 0;
// synthesis translate_off
`include "myip_v1_0_HLS_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //myip_v1_0_HLS

