// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myip_v1_0_HLS_myip_v1_0_HLS,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.910000,HLS_SYN_LAT=1228,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=120,HLS_SYN_LUT=461,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module myip_v1_0_HLS (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TREADY,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_pp0_stage0 = 7'd4;
parameter    ap_ST_fsm_state5 = 7'd8;
parameter    ap_ST_fsm_state6 = 7'd16;
parameter    ap_ST_fsm_state7 = 7'd32;
parameter    ap_ST_fsm_state8 = 7'd64;

input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

 reg    ap_rst_n_inv;
reg    S_AXIS_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln46_fu_246_p2;
reg    M_AXIS_TDATA_blk_n;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln63_fu_332_p2;
reg   [0:0] icmp_ln63_reg_541;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln63_1_fu_403_p2;
reg   [0:0] icmp_ln63_1_reg_556;
reg   [5:0] mat_RES_addr_1_reg_560;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln79_fu_481_p2;
reg   [0:0] icmp_ln79_reg_580;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_state2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln59_fu_314_p2;
reg    ap_condition_pp0_exit_iter0_state3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [31:0] mat_A_q0;
wire  signed [31:0] mat_B_q0;
wire   [23:0] mat_RES_d0;
wire   [23:0] mat_RES_q0;
wire   [63:0] zext_ln46_fu_258_p1;
wire   [0:0] tmp_fu_273_p3;
wire   [63:0] zext_ln54_fu_281_p1;
wire   [63:0] zext_ln65_fu_392_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln63_fu_377_p1;
wire   [63:0] zext_ln59_fu_360_p1;
wire   [63:0] zext_ln72_fu_476_p1;
wire   [0:0] icmp_ln72_fu_464_p2;
reg   [9:0] word_cnt_fu_110;
wire   [9:0] add_ln46_fu_252_p2;
wire    ap_CS_fsm_state1;
reg   [31:0] temp_fu_126;
wire   [31:0] temp_1_fu_434_p2;
reg   [3:0] k_fu_130;
wire   [3:0] k_1_fu_397_p2;
reg   [6:0] i_fu_134;
wire   [6:0] select_ln59_fu_352_p3;
reg   [9:0] indvar_flatten_fu_138;
wire   [9:0] add_ln59_fu_320_p2;
reg   [6:0] word_cnt_1_fu_142;
wire   [6:0] add_ln72_fu_470_p2;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
wire    ap_CS_fsm_state5;
reg    mat_A_we0_local;
reg    mat_A_ce0_local;
reg   [8:0] mat_A_address0_local;
reg    mat_B_we0_local;
reg    mat_B_ce0_local;
reg   [2:0] mat_B_address0_local;
reg    mat_RES_we0_local;
reg    mat_RES_ce0_local;
reg   [5:0] mat_RES_address0_local;
wire   [2:0] trunc_ln46_fu_263_p1;
wire   [6:0] add_ln59_1_fu_346_p2;
wire   [5:0] trunc_ln65_fu_365_p1;
wire   [3:0] select_ln60_fu_338_p3;
wire   [8:0] zext_ln63_1_fu_382_p1;
wire   [8:0] shl_ln_fu_369_p3;
wire   [8:0] add_ln65_fu_386_p2;
wire   [31:0] mul_ln65_fu_232_p2;
wire   [31:0] select_ln60_1_fu_427_p3;
reg   [6:0] ap_NS_fsm;
wire    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
wire   [31:0] M_AXIS_TDATA_int_regslice;
reg    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 word_cnt_fu_110 = 10'd0;
#0 temp_fu_126 = 32'd0;
#0 k_fu_130 = 4'd0;
#0 i_fu_134 = 7'd0;
#0 indvar_flatten_fu_138 = 10'd0;
#0 word_cnt_1_fu_142 = 7'd0;
end

myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
mat_A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_A_address0_local),
    .ce0(mat_A_ce0_local),
    .we0(mat_A_we0_local),
    .d0(S_AXIS_TDATA_int_regslice),
    .q0(mat_A_q0)
);

myip_v1_0_HLS_mat_B_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
mat_B_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_B_address0_local),
    .ce0(mat_B_ce0_local),
    .we0(mat_B_we0_local),
    .d0(S_AXIS_TDATA_int_regslice),
    .q0(mat_B_q0)
);

myip_v1_0_HLS_mat_RES_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_RES_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mat_RES_address0_local),
    .ce0(mat_RES_ce0_local),
    .we0(mat_RES_we0_local),
    .d0(mat_RES_d0),
    .q0(mat_RES_q0)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U1(
    .din0(mat_B_q0),
    .din1(mat_A_q0),
    .dout(mul_ln65_fu_232_p2)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(M_AXIS_TDATA_int_regslice),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

myip_v1_0_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(icmp_ln79_reg_580),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state3))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_134 <= 7'd0;
    end else if (((icmp_ln59_fu_314_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_134 <= select_ln59_fu_352_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        indvar_flatten_fu_138 <= 10'd0;
    end else if (((icmp_ln59_fu_314_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_fu_138 <= add_ln59_fu_320_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_fu_130 <= 4'd0;
    end else if (((icmp_ln59_fu_314_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_fu_130 <= k_1_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        temp_fu_126 <= 32'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        temp_fu_126 <= temp_1_fu_434_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        word_cnt_1_fu_142 <= 7'd0;
    end else if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln72_fu_464_p2 == 1'd0))) begin
        word_cnt_1_fu_142 <= add_ln72_fu_470_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        word_cnt_fu_110 <= 10'd0;
    end else if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        word_cnt_fu_110 <= add_ln46_fu_252_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln63_1_reg_556 <= icmp_ln63_1_fu_403_p2;
        icmp_ln63_reg_541 <= icmp_ln63_fu_332_p2;
        mat_RES_addr_1_reg_560 <= zext_ln59_fu_360_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        icmp_ln79_reg_580 <= icmp_ln79_fu_481_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7))) begin
        M_AXIS_TDATA_blk_n = M_AXIS_TREADY_int_regslice;
    end else begin
        M_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) & (1'b1 == M_AXIS_TREADY_int_regslice))) begin
        M_AXIS_TVALID_int_regslice = 1'b1;
    end else begin
        M_AXIS_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln46_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        S_AXIS_TDATA_blk_n = S_AXIS_TVALID_int_regslice;
    end else begin
        S_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        S_AXIS_TREADY_int_regslice = 1'b1;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

assign ap_ST_fsm_state1_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state2)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == M_AXIS_TREADY_int_regslice)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == M_AXIS_TREADY_int_regslice)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln59_fu_314_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_address0_local = zext_ln65_fu_392_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_A_address0_local = zext_ln46_fu_258_p1;
    end else begin
        mat_A_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mat_A_ce0_local = 1'b1;
    end else begin
        mat_A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_273_p3 == 1'd0))) begin
        mat_A_we0_local = 1'b1;
    end else begin
        mat_A_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_address0_local = zext_ln63_fu_377_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        mat_B_address0_local = zext_ln54_fu_281_p1;
    end else begin
        mat_B_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_state2) & (1'b1 == ap_CS_fsm_state2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        mat_B_ce0_local = 1'b1;
    end else begin
        mat_B_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (tmp_fu_273_p3 == 1'd1))) begin
        mat_B_we0_local = 1'b1;
    end else begin
        mat_B_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        mat_RES_address0_local = zext_ln72_fu_476_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        mat_RES_address0_local = mat_RES_addr_1_reg_560;
    end else begin
        mat_RES_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6)))) begin
        mat_RES_ce0_local = 1'b1;
    end else begin
        mat_RES_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln63_1_reg_556 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        mat_RES_we0_local = 1'b1;
    end else begin
        mat_RES_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_state2) & (icmp_ln46_fu_246_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((icmp_ln59_fu_314_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((icmp_ln59_fu_314_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln72_fu_464_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state6) & (icmp_ln72_fu_464_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (1'b1 == M_AXIS_TREADY_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (1'b1 == M_AXIS_TREADY_int_regslice))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TDATA_int_regslice = mat_RES_q0;

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign add_ln46_fu_252_p2 = (word_cnt_fu_110 + 10'd1);

assign add_ln59_1_fu_346_p2 = (i_fu_134 + 7'd1);

assign add_ln59_fu_320_p2 = (indvar_flatten_fu_138 + 10'd1);

assign add_ln65_fu_386_p2 = (zext_ln63_1_fu_382_p1 + shl_ln_fu_369_p3);

assign add_ln72_fu_470_p2 = (word_cnt_1_fu_142 + 7'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2 = ((icmp_ln46_fu_246_p2 == 1'd0) & (1'b0 == S_AXIS_TVALID_int_regslice));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln46_fu_246_p2 = ((word_cnt_fu_110 == 10'd520) ? 1'b1 : 1'b0);

assign icmp_ln59_fu_314_p2 = ((indvar_flatten_fu_138 == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln63_1_fu_403_p2 = ((k_1_fu_397_p2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_332_p2 = ((k_fu_130 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_464_p2 = ((word_cnt_1_fu_142 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_481_p2 = ((word_cnt_1_fu_142 == 7'd63) ? 1'b1 : 1'b0);

assign k_1_fu_397_p2 = (select_ln60_fu_338_p3 + 4'd1);

assign mat_RES_d0 = {{temp_1_fu_434_p2[31:8]}};

assign select_ln59_fu_352_p3 = ((icmp_ln63_fu_332_p2[0:0] == 1'b1) ? add_ln59_1_fu_346_p2 : i_fu_134);

assign select_ln60_1_fu_427_p3 = ((icmp_ln63_reg_541[0:0] == 1'b1) ? 32'd0 : temp_fu_126);

assign select_ln60_fu_338_p3 = ((icmp_ln63_fu_332_p2[0:0] == 1'b1) ? 4'd0 : k_fu_130);

assign shl_ln_fu_369_p3 = {{trunc_ln65_fu_365_p1}, {3'd0}};

assign temp_1_fu_434_p2 = (mul_ln65_fu_232_p2 + select_ln60_1_fu_427_p3);

assign tmp_fu_273_p3 = word_cnt_fu_110[32'd9];

assign trunc_ln46_fu_263_p1 = word_cnt_fu_110[2:0];

assign trunc_ln65_fu_365_p1 = select_ln59_fu_352_p3[5:0];

assign zext_ln46_fu_258_p1 = word_cnt_fu_110;

assign zext_ln54_fu_281_p1 = trunc_ln46_fu_263_p1;

assign zext_ln59_fu_360_p1 = select_ln59_fu_352_p3;

assign zext_ln63_1_fu_382_p1 = select_ln60_fu_338_p3;

assign zext_ln63_fu_377_p1 = select_ln60_fu_338_p3;

assign zext_ln65_fu_392_p1 = add_ln65_fu_386_p2;

assign zext_ln72_fu_476_p1 = word_cnt_1_fu_142;


reg find_kernel_block = 0;
// synthesis translate_off
`include "myip_v1_0_HLS_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //myip_v1_0_HLS

