// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myip_v2_0_HLS_myip_v2_0_HLS,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.404000,HLS_SYN_LAT=782,HLS_SYN_TPT=520,HLS_SYN_MEM=16,HLS_SYN_DSP=0,HLS_SYN_FF=11236,HLS_SYN_LUT=6450,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module myip_v2_0_HLS (
        ap_clk,
        ap_rst_n,
        S_AXIS_TDATA,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        M_AXIS_TDATA,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST,
        S_AXIS_TVALID,
        S_AXIS_TREADY,
        M_AXIS_TVALID,
        M_AXIS_TREADY
);


input   ap_clk;
input   ap_rst_n;
input  [31:0] S_AXIS_TDATA;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] M_AXIS_TDATA;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;
input   S_AXIS_TVALID;
output   S_AXIS_TREADY;
output   M_AXIS_TVALID;
input   M_AXIS_TREADY;

 reg    ap_rst_n_inv;
wire   [31:0] mat_A_i_q0;
wire   [31:0] mat_A_t_q0;
wire   [31:0] mat_A_1_i_q0;
wire   [31:0] mat_A_1_t_q0;
wire   [31:0] mat_A_2_i_q0;
wire   [31:0] mat_A_2_t_q0;
wire   [31:0] mat_A_3_i_q0;
wire   [31:0] mat_A_3_t_q0;
wire   [31:0] mat_A_4_i_q0;
wire   [31:0] mat_A_4_t_q0;
wire   [31:0] mat_A_5_i_q0;
wire   [31:0] mat_A_5_t_q0;
wire   [31:0] mat_A_6_i_q0;
wire   [31:0] mat_A_6_t_q0;
wire   [31:0] mat_A_7_i_q0;
wire   [31:0] mat_A_7_t_q0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_start;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_done;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_continue;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_idle;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_ready;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_d0;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_d0;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_d0;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_d0;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_d0;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_d0;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_d0;
wire   [5:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_address0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_ce0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_we0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_d0;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_S_AXIS_TREADY;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_0;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_1;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_2;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_3;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_4;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_5;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_6;
wire   [31:0] Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_7;
wire    ap_channel_done_p_loc24_channel;
wire    p_loc24_channel_full_n;
reg    ap_sync_reg_channel_write_p_loc24_channel;
wire    ap_sync_channel_write_p_loc24_channel;
wire    ap_channel_done_mat_A;
wire    Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_full_n;
reg    ap_sync_reg_channel_write_mat_A;
wire    ap_sync_channel_write_mat_A;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_ap_start;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_ap_done;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_ap_continue;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_ap_idle;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_0_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_0_ce0;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_1_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_1_ce0;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_2_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_2_ce0;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_3_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_3_ce0;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_4_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_4_ce0;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_5_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_5_ce0;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_6_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_6_ce0;
wire   [5:0] Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_7_address0;
wire    Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_7_ce0;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_0;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_1;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_2;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_3;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_4;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_5;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_6;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_7;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_8;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_9;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_10;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_11;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_12;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_13;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_14;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_15;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_16;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_17;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_18;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_19;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_20;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_21;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_22;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_23;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_24;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_25;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_26;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_27;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_28;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_29;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_30;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_31;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_32;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_33;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_34;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_35;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_36;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_37;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_38;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_39;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_40;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_41;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_42;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_43;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_44;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_45;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_46;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_47;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_48;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_49;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_50;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_51;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_52;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_53;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_54;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_55;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_56;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_57;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_58;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_59;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_60;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_61;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_62;
wire   [31:0] Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_63;
wire    ap_channel_done_mat_RES_0_0_loc_channel;
wire    mat_RES_0_0_loc_channel_full_n;
reg    ap_sync_reg_channel_write_mat_RES_0_0_loc_channel;
wire    ap_sync_channel_write_mat_RES_0_0_loc_channel;
wire    Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_start;
wire    Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_done;
wire    Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_continue;
wire    Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_idle;
wire    Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready;
wire   [31:0] Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TDATA;
wire    Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TVALID;
wire   [3:0] Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TKEEP;
wire   [3:0] Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TSTRB;
wire   [0:0] Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TLAST;
wire    mat_A_7_i_full_n;
wire    mat_A_7_t_empty_n;
wire    mat_A_6_i_full_n;
wire    mat_A_6_t_empty_n;
wire    mat_A_5_i_full_n;
wire    mat_A_5_t_empty_n;
wire    mat_A_4_i_full_n;
wire    mat_A_4_t_empty_n;
wire    mat_A_3_i_full_n;
wire    mat_A_3_t_empty_n;
wire    mat_A_2_i_full_n;
wire    mat_A_2_t_empty_n;
wire    mat_A_1_i_full_n;
wire    mat_A_1_t_empty_n;
wire    mat_A_i_full_n;
wire    mat_A_t_empty_n;
wire    p_loc_channel_full_n;
wire   [31:0] p_loc_channel_dout;
wire    p_loc_channel_empty_n;
wire   [2:0] p_loc_channel_num_data_valid;
wire   [2:0] p_loc_channel_fifo_cap;
wire    p_loc18_channel_full_n;
wire   [31:0] p_loc18_channel_dout;
wire    p_loc18_channel_empty_n;
wire   [2:0] p_loc18_channel_num_data_valid;
wire   [2:0] p_loc18_channel_fifo_cap;
wire    p_loc19_channel_full_n;
wire   [31:0] p_loc19_channel_dout;
wire    p_loc19_channel_empty_n;
wire   [2:0] p_loc19_channel_num_data_valid;
wire   [2:0] p_loc19_channel_fifo_cap;
wire    p_loc20_channel_full_n;
wire   [31:0] p_loc20_channel_dout;
wire    p_loc20_channel_empty_n;
wire   [2:0] p_loc20_channel_num_data_valid;
wire   [2:0] p_loc20_channel_fifo_cap;
wire    p_loc21_channel_full_n;
wire   [31:0] p_loc21_channel_dout;
wire    p_loc21_channel_empty_n;
wire   [2:0] p_loc21_channel_num_data_valid;
wire   [2:0] p_loc21_channel_fifo_cap;
wire    p_loc22_channel_full_n;
wire   [31:0] p_loc22_channel_dout;
wire    p_loc22_channel_empty_n;
wire   [2:0] p_loc22_channel_num_data_valid;
wire   [2:0] p_loc22_channel_fifo_cap;
wire    p_loc23_channel_full_n;
wire   [31:0] p_loc23_channel_dout;
wire    p_loc23_channel_empty_n;
wire   [2:0] p_loc23_channel_num_data_valid;
wire   [2:0] p_loc23_channel_fifo_cap;
wire   [31:0] p_loc24_channel_dout;
wire    p_loc24_channel_empty_n;
wire   [2:0] p_loc24_channel_num_data_valid;
wire   [2:0] p_loc24_channel_fifo_cap;
wire    mat_RES_63_0_loc_channel_full_n;
wire   [31:0] mat_RES_63_0_loc_channel_dout;
wire    mat_RES_63_0_loc_channel_empty_n;
wire   [2:0] mat_RES_63_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_63_0_loc_channel_fifo_cap;
wire    mat_RES_62_0_loc_channel_full_n;
wire   [31:0] mat_RES_62_0_loc_channel_dout;
wire    mat_RES_62_0_loc_channel_empty_n;
wire   [2:0] mat_RES_62_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_62_0_loc_channel_fifo_cap;
wire    mat_RES_61_0_loc_channel_full_n;
wire   [31:0] mat_RES_61_0_loc_channel_dout;
wire    mat_RES_61_0_loc_channel_empty_n;
wire   [2:0] mat_RES_61_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_61_0_loc_channel_fifo_cap;
wire    mat_RES_60_0_loc_channel_full_n;
wire   [31:0] mat_RES_60_0_loc_channel_dout;
wire    mat_RES_60_0_loc_channel_empty_n;
wire   [2:0] mat_RES_60_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_60_0_loc_channel_fifo_cap;
wire    mat_RES_59_0_loc_channel_full_n;
wire   [31:0] mat_RES_59_0_loc_channel_dout;
wire    mat_RES_59_0_loc_channel_empty_n;
wire   [2:0] mat_RES_59_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_59_0_loc_channel_fifo_cap;
wire    mat_RES_58_0_loc_channel_full_n;
wire   [31:0] mat_RES_58_0_loc_channel_dout;
wire    mat_RES_58_0_loc_channel_empty_n;
wire   [2:0] mat_RES_58_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_58_0_loc_channel_fifo_cap;
wire    mat_RES_57_0_loc_channel_full_n;
wire   [31:0] mat_RES_57_0_loc_channel_dout;
wire    mat_RES_57_0_loc_channel_empty_n;
wire   [2:0] mat_RES_57_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_57_0_loc_channel_fifo_cap;
wire    mat_RES_56_0_loc_channel_full_n;
wire   [31:0] mat_RES_56_0_loc_channel_dout;
wire    mat_RES_56_0_loc_channel_empty_n;
wire   [2:0] mat_RES_56_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_56_0_loc_channel_fifo_cap;
wire    mat_RES_55_0_loc_channel_full_n;
wire   [31:0] mat_RES_55_0_loc_channel_dout;
wire    mat_RES_55_0_loc_channel_empty_n;
wire   [2:0] mat_RES_55_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_55_0_loc_channel_fifo_cap;
wire    mat_RES_54_0_loc_channel_full_n;
wire   [31:0] mat_RES_54_0_loc_channel_dout;
wire    mat_RES_54_0_loc_channel_empty_n;
wire   [2:0] mat_RES_54_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_54_0_loc_channel_fifo_cap;
wire    mat_RES_53_0_loc_channel_full_n;
wire   [31:0] mat_RES_53_0_loc_channel_dout;
wire    mat_RES_53_0_loc_channel_empty_n;
wire   [2:0] mat_RES_53_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_53_0_loc_channel_fifo_cap;
wire    mat_RES_52_0_loc_channel_full_n;
wire   [31:0] mat_RES_52_0_loc_channel_dout;
wire    mat_RES_52_0_loc_channel_empty_n;
wire   [2:0] mat_RES_52_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_52_0_loc_channel_fifo_cap;
wire    mat_RES_51_0_loc_channel_full_n;
wire   [31:0] mat_RES_51_0_loc_channel_dout;
wire    mat_RES_51_0_loc_channel_empty_n;
wire   [2:0] mat_RES_51_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_51_0_loc_channel_fifo_cap;
wire    mat_RES_50_0_loc_channel_full_n;
wire   [31:0] mat_RES_50_0_loc_channel_dout;
wire    mat_RES_50_0_loc_channel_empty_n;
wire   [2:0] mat_RES_50_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_50_0_loc_channel_fifo_cap;
wire    mat_RES_49_0_loc_channel_full_n;
wire   [31:0] mat_RES_49_0_loc_channel_dout;
wire    mat_RES_49_0_loc_channel_empty_n;
wire   [2:0] mat_RES_49_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_49_0_loc_channel_fifo_cap;
wire    mat_RES_48_0_loc_channel_full_n;
wire   [31:0] mat_RES_48_0_loc_channel_dout;
wire    mat_RES_48_0_loc_channel_empty_n;
wire   [2:0] mat_RES_48_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_48_0_loc_channel_fifo_cap;
wire    mat_RES_47_0_loc_channel_full_n;
wire   [31:0] mat_RES_47_0_loc_channel_dout;
wire    mat_RES_47_0_loc_channel_empty_n;
wire   [2:0] mat_RES_47_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_47_0_loc_channel_fifo_cap;
wire    mat_RES_46_0_loc_channel_full_n;
wire   [31:0] mat_RES_46_0_loc_channel_dout;
wire    mat_RES_46_0_loc_channel_empty_n;
wire   [2:0] mat_RES_46_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_46_0_loc_channel_fifo_cap;
wire    mat_RES_45_0_loc_channel_full_n;
wire   [31:0] mat_RES_45_0_loc_channel_dout;
wire    mat_RES_45_0_loc_channel_empty_n;
wire   [2:0] mat_RES_45_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_45_0_loc_channel_fifo_cap;
wire    mat_RES_44_0_loc_channel_full_n;
wire   [31:0] mat_RES_44_0_loc_channel_dout;
wire    mat_RES_44_0_loc_channel_empty_n;
wire   [2:0] mat_RES_44_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_44_0_loc_channel_fifo_cap;
wire    mat_RES_43_0_loc_channel_full_n;
wire   [31:0] mat_RES_43_0_loc_channel_dout;
wire    mat_RES_43_0_loc_channel_empty_n;
wire   [2:0] mat_RES_43_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_43_0_loc_channel_fifo_cap;
wire    mat_RES_42_0_loc_channel_full_n;
wire   [31:0] mat_RES_42_0_loc_channel_dout;
wire    mat_RES_42_0_loc_channel_empty_n;
wire   [2:0] mat_RES_42_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_42_0_loc_channel_fifo_cap;
wire    mat_RES_41_0_loc_channel_full_n;
wire   [31:0] mat_RES_41_0_loc_channel_dout;
wire    mat_RES_41_0_loc_channel_empty_n;
wire   [2:0] mat_RES_41_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_41_0_loc_channel_fifo_cap;
wire    mat_RES_40_0_loc_channel_full_n;
wire   [31:0] mat_RES_40_0_loc_channel_dout;
wire    mat_RES_40_0_loc_channel_empty_n;
wire   [2:0] mat_RES_40_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_40_0_loc_channel_fifo_cap;
wire    mat_RES_39_0_loc_channel_full_n;
wire   [31:0] mat_RES_39_0_loc_channel_dout;
wire    mat_RES_39_0_loc_channel_empty_n;
wire   [2:0] mat_RES_39_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_39_0_loc_channel_fifo_cap;
wire    mat_RES_38_0_loc_channel_full_n;
wire   [31:0] mat_RES_38_0_loc_channel_dout;
wire    mat_RES_38_0_loc_channel_empty_n;
wire   [2:0] mat_RES_38_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_38_0_loc_channel_fifo_cap;
wire    mat_RES_37_0_loc_channel_full_n;
wire   [31:0] mat_RES_37_0_loc_channel_dout;
wire    mat_RES_37_0_loc_channel_empty_n;
wire   [2:0] mat_RES_37_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_37_0_loc_channel_fifo_cap;
wire    mat_RES_36_0_loc_channel_full_n;
wire   [31:0] mat_RES_36_0_loc_channel_dout;
wire    mat_RES_36_0_loc_channel_empty_n;
wire   [2:0] mat_RES_36_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_36_0_loc_channel_fifo_cap;
wire    mat_RES_35_0_loc_channel_full_n;
wire   [31:0] mat_RES_35_0_loc_channel_dout;
wire    mat_RES_35_0_loc_channel_empty_n;
wire   [2:0] mat_RES_35_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_35_0_loc_channel_fifo_cap;
wire    mat_RES_34_0_loc_channel_full_n;
wire   [31:0] mat_RES_34_0_loc_channel_dout;
wire    mat_RES_34_0_loc_channel_empty_n;
wire   [2:0] mat_RES_34_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_34_0_loc_channel_fifo_cap;
wire    mat_RES_33_0_loc_channel_full_n;
wire   [31:0] mat_RES_33_0_loc_channel_dout;
wire    mat_RES_33_0_loc_channel_empty_n;
wire   [2:0] mat_RES_33_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_33_0_loc_channel_fifo_cap;
wire    mat_RES_32_0_loc_channel_full_n;
wire   [31:0] mat_RES_32_0_loc_channel_dout;
wire    mat_RES_32_0_loc_channel_empty_n;
wire   [2:0] mat_RES_32_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_32_0_loc_channel_fifo_cap;
wire    mat_RES_31_0_loc_channel_full_n;
wire   [31:0] mat_RES_31_0_loc_channel_dout;
wire    mat_RES_31_0_loc_channel_empty_n;
wire   [2:0] mat_RES_31_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_31_0_loc_channel_fifo_cap;
wire    mat_RES_30_0_loc_channel_full_n;
wire   [31:0] mat_RES_30_0_loc_channel_dout;
wire    mat_RES_30_0_loc_channel_empty_n;
wire   [2:0] mat_RES_30_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_30_0_loc_channel_fifo_cap;
wire    mat_RES_29_0_loc_channel_full_n;
wire   [31:0] mat_RES_29_0_loc_channel_dout;
wire    mat_RES_29_0_loc_channel_empty_n;
wire   [2:0] mat_RES_29_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_29_0_loc_channel_fifo_cap;
wire    mat_RES_28_0_loc_channel_full_n;
wire   [31:0] mat_RES_28_0_loc_channel_dout;
wire    mat_RES_28_0_loc_channel_empty_n;
wire   [2:0] mat_RES_28_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_28_0_loc_channel_fifo_cap;
wire    mat_RES_27_0_loc_channel_full_n;
wire   [31:0] mat_RES_27_0_loc_channel_dout;
wire    mat_RES_27_0_loc_channel_empty_n;
wire   [2:0] mat_RES_27_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_27_0_loc_channel_fifo_cap;
wire    mat_RES_26_0_loc_channel_full_n;
wire   [31:0] mat_RES_26_0_loc_channel_dout;
wire    mat_RES_26_0_loc_channel_empty_n;
wire   [2:0] mat_RES_26_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_26_0_loc_channel_fifo_cap;
wire    mat_RES_25_0_loc_channel_full_n;
wire   [31:0] mat_RES_25_0_loc_channel_dout;
wire    mat_RES_25_0_loc_channel_empty_n;
wire   [2:0] mat_RES_25_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_25_0_loc_channel_fifo_cap;
wire    mat_RES_24_0_loc_channel_full_n;
wire   [31:0] mat_RES_24_0_loc_channel_dout;
wire    mat_RES_24_0_loc_channel_empty_n;
wire   [2:0] mat_RES_24_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_24_0_loc_channel_fifo_cap;
wire    mat_RES_23_0_loc_channel_full_n;
wire   [31:0] mat_RES_23_0_loc_channel_dout;
wire    mat_RES_23_0_loc_channel_empty_n;
wire   [2:0] mat_RES_23_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_23_0_loc_channel_fifo_cap;
wire    mat_RES_22_0_loc_channel_full_n;
wire   [31:0] mat_RES_22_0_loc_channel_dout;
wire    mat_RES_22_0_loc_channel_empty_n;
wire   [2:0] mat_RES_22_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_22_0_loc_channel_fifo_cap;
wire    mat_RES_21_0_loc_channel_full_n;
wire   [31:0] mat_RES_21_0_loc_channel_dout;
wire    mat_RES_21_0_loc_channel_empty_n;
wire   [2:0] mat_RES_21_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_21_0_loc_channel_fifo_cap;
wire    mat_RES_20_0_loc_channel_full_n;
wire   [31:0] mat_RES_20_0_loc_channel_dout;
wire    mat_RES_20_0_loc_channel_empty_n;
wire   [2:0] mat_RES_20_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_20_0_loc_channel_fifo_cap;
wire    mat_RES_19_0_loc_channel_full_n;
wire   [31:0] mat_RES_19_0_loc_channel_dout;
wire    mat_RES_19_0_loc_channel_empty_n;
wire   [2:0] mat_RES_19_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_19_0_loc_channel_fifo_cap;
wire    mat_RES_18_0_loc_channel_full_n;
wire   [31:0] mat_RES_18_0_loc_channel_dout;
wire    mat_RES_18_0_loc_channel_empty_n;
wire   [2:0] mat_RES_18_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_18_0_loc_channel_fifo_cap;
wire    mat_RES_17_0_loc_channel_full_n;
wire   [31:0] mat_RES_17_0_loc_channel_dout;
wire    mat_RES_17_0_loc_channel_empty_n;
wire   [2:0] mat_RES_17_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_17_0_loc_channel_fifo_cap;
wire    mat_RES_16_0_loc_channel_full_n;
wire   [31:0] mat_RES_16_0_loc_channel_dout;
wire    mat_RES_16_0_loc_channel_empty_n;
wire   [2:0] mat_RES_16_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_16_0_loc_channel_fifo_cap;
wire    mat_RES_15_0_loc_channel_full_n;
wire   [31:0] mat_RES_15_0_loc_channel_dout;
wire    mat_RES_15_0_loc_channel_empty_n;
wire   [2:0] mat_RES_15_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_15_0_loc_channel_fifo_cap;
wire    mat_RES_14_0_loc_channel_full_n;
wire   [31:0] mat_RES_14_0_loc_channel_dout;
wire    mat_RES_14_0_loc_channel_empty_n;
wire   [2:0] mat_RES_14_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_14_0_loc_channel_fifo_cap;
wire    mat_RES_13_0_loc_channel_full_n;
wire   [31:0] mat_RES_13_0_loc_channel_dout;
wire    mat_RES_13_0_loc_channel_empty_n;
wire   [2:0] mat_RES_13_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_13_0_loc_channel_fifo_cap;
wire    mat_RES_12_0_loc_channel_full_n;
wire   [31:0] mat_RES_12_0_loc_channel_dout;
wire    mat_RES_12_0_loc_channel_empty_n;
wire   [2:0] mat_RES_12_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_12_0_loc_channel_fifo_cap;
wire    mat_RES_11_0_loc_channel_full_n;
wire   [31:0] mat_RES_11_0_loc_channel_dout;
wire    mat_RES_11_0_loc_channel_empty_n;
wire   [2:0] mat_RES_11_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_11_0_loc_channel_fifo_cap;
wire    mat_RES_10_0_loc_channel_full_n;
wire   [31:0] mat_RES_10_0_loc_channel_dout;
wire    mat_RES_10_0_loc_channel_empty_n;
wire   [2:0] mat_RES_10_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_10_0_loc_channel_fifo_cap;
wire    mat_RES_9_0_loc_channel_full_n;
wire   [31:0] mat_RES_9_0_loc_channel_dout;
wire    mat_RES_9_0_loc_channel_empty_n;
wire   [2:0] mat_RES_9_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_9_0_loc_channel_fifo_cap;
wire    mat_RES_8_0_loc_channel_full_n;
wire   [31:0] mat_RES_8_0_loc_channel_dout;
wire    mat_RES_8_0_loc_channel_empty_n;
wire   [2:0] mat_RES_8_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_8_0_loc_channel_fifo_cap;
wire    mat_RES_7_0_loc_channel_full_n;
wire   [31:0] mat_RES_7_0_loc_channel_dout;
wire    mat_RES_7_0_loc_channel_empty_n;
wire   [2:0] mat_RES_7_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_7_0_loc_channel_fifo_cap;
wire    mat_RES_6_0_loc_channel_full_n;
wire   [31:0] mat_RES_6_0_loc_channel_dout;
wire    mat_RES_6_0_loc_channel_empty_n;
wire   [2:0] mat_RES_6_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_6_0_loc_channel_fifo_cap;
wire    mat_RES_5_0_loc_channel_full_n;
wire   [31:0] mat_RES_5_0_loc_channel_dout;
wire    mat_RES_5_0_loc_channel_empty_n;
wire   [2:0] mat_RES_5_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_5_0_loc_channel_fifo_cap;
wire    mat_RES_4_0_loc_channel_full_n;
wire   [31:0] mat_RES_4_0_loc_channel_dout;
wire    mat_RES_4_0_loc_channel_empty_n;
wire   [2:0] mat_RES_4_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_4_0_loc_channel_fifo_cap;
wire    mat_RES_3_0_loc_channel_full_n;
wire   [31:0] mat_RES_3_0_loc_channel_dout;
wire    mat_RES_3_0_loc_channel_empty_n;
wire   [2:0] mat_RES_3_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_3_0_loc_channel_fifo_cap;
wire    mat_RES_2_0_loc_channel_full_n;
wire   [31:0] mat_RES_2_0_loc_channel_dout;
wire    mat_RES_2_0_loc_channel_empty_n;
wire   [2:0] mat_RES_2_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_2_0_loc_channel_fifo_cap;
wire    mat_RES_1_0_loc_channel_full_n;
wire   [31:0] mat_RES_1_0_loc_channel_dout;
wire    mat_RES_1_0_loc_channel_empty_n;
wire   [2:0] mat_RES_1_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_1_0_loc_channel_fifo_cap;
wire   [31:0] mat_RES_0_0_loc_channel_dout;
wire    mat_RES_0_0_loc_channel_empty_n;
wire   [2:0] mat_RES_0_0_loc_channel_num_data_valid;
wire   [2:0] mat_RES_0_0_loc_channel_fifo_cap;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_p_loc24_channel = 1'b0;
#0 ap_sync_reg_channel_write_mat_A = 1'b0;
#0 ap_sync_reg_channel_write_mat_RES_0_0_loc_channel = 1'b0;
end

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_d0),
    .i_q0(mat_A_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_0_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_0_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_d0),
    .i_q0(mat_A_1_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_1_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_1_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_1_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_1_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_1_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_d0),
    .i_q0(mat_A_2_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_2_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_2_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_2_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_2_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_2_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_d0),
    .i_q0(mat_A_3_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_3_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_3_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_3_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_3_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_3_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_d0),
    .i_q0(mat_A_4_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_4_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_4_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_4_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_4_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_4_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_5_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_d0),
    .i_q0(mat_A_5_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_5_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_5_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_5_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_5_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_5_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_d0),
    .i_q0(mat_A_6_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_6_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_6_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_6_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_6_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_6_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_mat_A_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mat_A_7_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_address0),
    .i_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_ce0),
    .i_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_we0),
    .i_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_d0),
    .i_q0(mat_A_7_i_q0),
    .t_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_7_address0),
    .t_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_7_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(mat_A_7_t_q0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(mat_A_7_i_full_n),
    .i_write(ap_channel_done_mat_A),
    .t_empty_n(mat_A_7_t_empty_n),
    .t_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready)
);

myip_v2_0_HLS_Loop_myip_v2_0_HLS_read_inputs_proc Loop_myip_v2_0_HLS_read_inputs_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_start),
    .ap_done(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_done),
    .ap_continue(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_continue),
    .ap_idle(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_idle),
    .ap_ready(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_ready),
    .S_AXIS_TVALID(S_AXIS_TVALID),
    .mat_A_7_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_address0),
    .mat_A_7_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_ce0),
    .mat_A_7_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_we0),
    .mat_A_7_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_7_d0),
    .mat_A_6_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_address0),
    .mat_A_6_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_ce0),
    .mat_A_6_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_we0),
    .mat_A_6_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_6_d0),
    .mat_A_5_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_address0),
    .mat_A_5_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_ce0),
    .mat_A_5_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_we0),
    .mat_A_5_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_5_d0),
    .mat_A_4_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_address0),
    .mat_A_4_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_ce0),
    .mat_A_4_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_we0),
    .mat_A_4_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_4_d0),
    .mat_A_3_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_address0),
    .mat_A_3_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_ce0),
    .mat_A_3_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_we0),
    .mat_A_3_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_3_d0),
    .mat_A_2_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_address0),
    .mat_A_2_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_ce0),
    .mat_A_2_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_we0),
    .mat_A_2_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_2_d0),
    .mat_A_1_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_address0),
    .mat_A_1_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_ce0),
    .mat_A_1_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_we0),
    .mat_A_1_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_1_d0),
    .mat_A_0_address0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_address0),
    .mat_A_0_ce0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_ce0),
    .mat_A_0_we0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_we0),
    .mat_A_0_d0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_d0),
    .S_AXIS_TDATA(S_AXIS_TDATA),
    .S_AXIS_TREADY(Loop_myip_v2_0_HLS_read_inputs_proc_U0_S_AXIS_TREADY),
    .S_AXIS_TKEEP(S_AXIS_TKEEP),
    .S_AXIS_TSTRB(S_AXIS_TSTRB),
    .S_AXIS_TLAST(S_AXIS_TLAST),
    .ap_return_0(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_0),
    .ap_return_1(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_1),
    .ap_return_2(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_2),
    .ap_return_3(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_3),
    .ap_return_4(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_4),
    .ap_return_5(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_5),
    .ap_return_6(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_6),
    .ap_return_7(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_7)
);

myip_v2_0_HLS_Loop_myip_v2_0_HLS_compute_proc Loop_myip_v2_0_HLS_compute_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_myip_v2_0_HLS_compute_proc_U0_ap_start),
    .ap_done(Loop_myip_v2_0_HLS_compute_proc_U0_ap_done),
    .ap_continue(Loop_myip_v2_0_HLS_compute_proc_U0_ap_continue),
    .ap_idle(Loop_myip_v2_0_HLS_compute_proc_U0_ap_idle),
    .ap_ready(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .p_read(p_loc_channel_dout),
    .p_read1(p_loc18_channel_dout),
    .p_read2(p_loc19_channel_dout),
    .p_read3(p_loc20_channel_dout),
    .p_read4(p_loc21_channel_dout),
    .p_read5(p_loc22_channel_dout),
    .p_read6(p_loc24_channel_dout),
    .p_read7(p_loc23_channel_dout),
    .mat_A_0_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_0_address0),
    .mat_A_0_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_0_ce0),
    .mat_A_0_q0(mat_A_t_q0),
    .mat_A_1_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_1_address0),
    .mat_A_1_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_1_ce0),
    .mat_A_1_q0(mat_A_1_t_q0),
    .mat_A_2_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_2_address0),
    .mat_A_2_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_2_ce0),
    .mat_A_2_q0(mat_A_2_t_q0),
    .mat_A_3_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_3_address0),
    .mat_A_3_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_3_ce0),
    .mat_A_3_q0(mat_A_3_t_q0),
    .mat_A_4_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_4_address0),
    .mat_A_4_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_4_ce0),
    .mat_A_4_q0(mat_A_4_t_q0),
    .mat_A_5_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_5_address0),
    .mat_A_5_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_5_ce0),
    .mat_A_5_q0(mat_A_5_t_q0),
    .mat_A_6_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_6_address0),
    .mat_A_6_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_6_ce0),
    .mat_A_6_q0(mat_A_6_t_q0),
    .mat_A_7_address0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_7_address0),
    .mat_A_7_ce0(Loop_myip_v2_0_HLS_compute_proc_U0_mat_A_7_ce0),
    .mat_A_7_q0(mat_A_7_t_q0),
    .ap_return_0(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_0),
    .ap_return_1(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_1),
    .ap_return_2(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_2),
    .ap_return_3(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_3),
    .ap_return_4(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_4),
    .ap_return_5(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_5),
    .ap_return_6(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_6),
    .ap_return_7(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_7),
    .ap_return_8(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_8),
    .ap_return_9(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_9),
    .ap_return_10(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_10),
    .ap_return_11(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_11),
    .ap_return_12(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_12),
    .ap_return_13(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_13),
    .ap_return_14(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_14),
    .ap_return_15(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_15),
    .ap_return_16(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_16),
    .ap_return_17(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_17),
    .ap_return_18(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_18),
    .ap_return_19(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_19),
    .ap_return_20(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_20),
    .ap_return_21(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_21),
    .ap_return_22(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_22),
    .ap_return_23(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_23),
    .ap_return_24(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_24),
    .ap_return_25(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_25),
    .ap_return_26(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_26),
    .ap_return_27(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_27),
    .ap_return_28(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_28),
    .ap_return_29(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_29),
    .ap_return_30(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_30),
    .ap_return_31(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_31),
    .ap_return_32(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_32),
    .ap_return_33(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_33),
    .ap_return_34(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_34),
    .ap_return_35(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_35),
    .ap_return_36(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_36),
    .ap_return_37(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_37),
    .ap_return_38(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_38),
    .ap_return_39(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_39),
    .ap_return_40(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_40),
    .ap_return_41(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_41),
    .ap_return_42(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_42),
    .ap_return_43(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_43),
    .ap_return_44(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_44),
    .ap_return_45(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_45),
    .ap_return_46(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_46),
    .ap_return_47(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_47),
    .ap_return_48(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_48),
    .ap_return_49(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_49),
    .ap_return_50(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_50),
    .ap_return_51(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_51),
    .ap_return_52(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_52),
    .ap_return_53(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_53),
    .ap_return_54(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_54),
    .ap_return_55(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_55),
    .ap_return_56(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_56),
    .ap_return_57(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_57),
    .ap_return_58(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_58),
    .ap_return_59(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_59),
    .ap_return_60(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_60),
    .ap_return_61(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_61),
    .ap_return_62(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_62),
    .ap_return_63(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_63)
);

myip_v2_0_HLS_Loop_myip_v2_0_HLS_write_outputs_proc Loop_myip_v2_0_HLS_write_outputs_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_start),
    .ap_done(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_done),
    .ap_continue(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_continue),
    .ap_idle(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_idle),
    .ap_ready(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .M_AXIS_TREADY(M_AXIS_TREADY),
    .p_read(mat_RES_0_0_loc_channel_dout),
    .p_read1(mat_RES_1_0_loc_channel_dout),
    .p_read2(mat_RES_2_0_loc_channel_dout),
    .p_read3(mat_RES_3_0_loc_channel_dout),
    .p_read4(mat_RES_4_0_loc_channel_dout),
    .p_read5(mat_RES_5_0_loc_channel_dout),
    .p_read6(mat_RES_6_0_loc_channel_dout),
    .p_read7(mat_RES_7_0_loc_channel_dout),
    .p_read8(mat_RES_8_0_loc_channel_dout),
    .p_read9(mat_RES_9_0_loc_channel_dout),
    .p_read10(mat_RES_10_0_loc_channel_dout),
    .p_read11(mat_RES_11_0_loc_channel_dout),
    .p_read12(mat_RES_12_0_loc_channel_dout),
    .p_read13(mat_RES_13_0_loc_channel_dout),
    .p_read14(mat_RES_14_0_loc_channel_dout),
    .p_read15(mat_RES_15_0_loc_channel_dout),
    .p_read16(mat_RES_16_0_loc_channel_dout),
    .p_read17(mat_RES_17_0_loc_channel_dout),
    .p_read18(mat_RES_18_0_loc_channel_dout),
    .p_read19(mat_RES_19_0_loc_channel_dout),
    .p_read20(mat_RES_20_0_loc_channel_dout),
    .p_read21(mat_RES_21_0_loc_channel_dout),
    .p_read22(mat_RES_22_0_loc_channel_dout),
    .p_read23(mat_RES_23_0_loc_channel_dout),
    .p_read24(mat_RES_24_0_loc_channel_dout),
    .p_read25(mat_RES_25_0_loc_channel_dout),
    .p_read26(mat_RES_26_0_loc_channel_dout),
    .p_read27(mat_RES_27_0_loc_channel_dout),
    .p_read28(mat_RES_28_0_loc_channel_dout),
    .p_read29(mat_RES_29_0_loc_channel_dout),
    .p_read30(mat_RES_30_0_loc_channel_dout),
    .p_read31(mat_RES_31_0_loc_channel_dout),
    .p_read32(mat_RES_32_0_loc_channel_dout),
    .p_read33(mat_RES_33_0_loc_channel_dout),
    .p_read34(mat_RES_34_0_loc_channel_dout),
    .p_read35(mat_RES_35_0_loc_channel_dout),
    .p_read36(mat_RES_36_0_loc_channel_dout),
    .p_read37(mat_RES_37_0_loc_channel_dout),
    .p_read38(mat_RES_38_0_loc_channel_dout),
    .p_read39(mat_RES_39_0_loc_channel_dout),
    .p_read40(mat_RES_40_0_loc_channel_dout),
    .p_read41(mat_RES_41_0_loc_channel_dout),
    .p_read42(mat_RES_42_0_loc_channel_dout),
    .p_read43(mat_RES_43_0_loc_channel_dout),
    .p_read44(mat_RES_44_0_loc_channel_dout),
    .p_read45(mat_RES_45_0_loc_channel_dout),
    .p_read46(mat_RES_46_0_loc_channel_dout),
    .p_read47(mat_RES_47_0_loc_channel_dout),
    .p_read48(mat_RES_48_0_loc_channel_dout),
    .p_read49(mat_RES_49_0_loc_channel_dout),
    .p_read50(mat_RES_50_0_loc_channel_dout),
    .p_read51(mat_RES_51_0_loc_channel_dout),
    .p_read52(mat_RES_52_0_loc_channel_dout),
    .p_read53(mat_RES_53_0_loc_channel_dout),
    .p_read54(mat_RES_54_0_loc_channel_dout),
    .p_read55(mat_RES_55_0_loc_channel_dout),
    .p_read56(mat_RES_56_0_loc_channel_dout),
    .p_read57(mat_RES_57_0_loc_channel_dout),
    .p_read58(mat_RES_58_0_loc_channel_dout),
    .p_read59(mat_RES_59_0_loc_channel_dout),
    .p_read60(mat_RES_60_0_loc_channel_dout),
    .p_read61(mat_RES_61_0_loc_channel_dout),
    .p_read62(mat_RES_62_0_loc_channel_dout),
    .p_read63(mat_RES_63_0_loc_channel_dout),
    .M_AXIS_TDATA(Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TDATA),
    .M_AXIS_TVALID(Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TVALID),
    .M_AXIS_TKEEP(Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TKEEP),
    .M_AXIS_TSTRB(Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TSTRB),
    .M_AXIS_TLAST(Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TLAST)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_0),
    .if_full_n(p_loc_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc_channel_dout),
    .if_empty_n(p_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc_channel_num_data_valid),
    .if_fifo_cap(p_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc18_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_1),
    .if_full_n(p_loc18_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc18_channel_dout),
    .if_empty_n(p_loc18_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc18_channel_num_data_valid),
    .if_fifo_cap(p_loc18_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc19_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_2),
    .if_full_n(p_loc19_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc19_channel_dout),
    .if_empty_n(p_loc19_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc19_channel_num_data_valid),
    .if_fifo_cap(p_loc19_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc20_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_3),
    .if_full_n(p_loc20_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc20_channel_dout),
    .if_empty_n(p_loc20_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc20_channel_num_data_valid),
    .if_fifo_cap(p_loc20_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc21_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_4),
    .if_full_n(p_loc21_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc21_channel_dout),
    .if_empty_n(p_loc21_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc21_channel_num_data_valid),
    .if_fifo_cap(p_loc21_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc22_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_5),
    .if_full_n(p_loc22_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc22_channel_dout),
    .if_empty_n(p_loc22_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc22_channel_num_data_valid),
    .if_fifo_cap(p_loc22_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc23_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_6),
    .if_full_n(p_loc23_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc23_channel_dout),
    .if_empty_n(p_loc23_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc23_channel_num_data_valid),
    .if_fifo_cap(p_loc23_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S p_loc24_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_return_7),
    .if_full_n(p_loc24_channel_full_n),
    .if_write(ap_channel_done_p_loc24_channel),
    .if_dout(p_loc24_channel_dout),
    .if_empty_n(p_loc24_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_compute_proc_U0_ap_ready),
    .if_num_data_valid(p_loc24_channel_num_data_valid),
    .if_fifo_cap(p_loc24_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_63_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_0),
    .if_full_n(mat_RES_63_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_63_0_loc_channel_dout),
    .if_empty_n(mat_RES_63_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_63_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_63_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_62_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_1),
    .if_full_n(mat_RES_62_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_62_0_loc_channel_dout),
    .if_empty_n(mat_RES_62_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_62_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_62_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_61_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_2),
    .if_full_n(mat_RES_61_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_61_0_loc_channel_dout),
    .if_empty_n(mat_RES_61_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_61_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_61_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_60_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_3),
    .if_full_n(mat_RES_60_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_60_0_loc_channel_dout),
    .if_empty_n(mat_RES_60_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_60_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_60_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_59_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_4),
    .if_full_n(mat_RES_59_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_59_0_loc_channel_dout),
    .if_empty_n(mat_RES_59_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_59_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_59_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_58_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_5),
    .if_full_n(mat_RES_58_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_58_0_loc_channel_dout),
    .if_empty_n(mat_RES_58_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_58_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_58_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_57_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_6),
    .if_full_n(mat_RES_57_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_57_0_loc_channel_dout),
    .if_empty_n(mat_RES_57_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_57_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_57_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_56_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_7),
    .if_full_n(mat_RES_56_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_56_0_loc_channel_dout),
    .if_empty_n(mat_RES_56_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_56_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_56_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_55_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_8),
    .if_full_n(mat_RES_55_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_55_0_loc_channel_dout),
    .if_empty_n(mat_RES_55_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_55_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_55_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_54_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_9),
    .if_full_n(mat_RES_54_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_54_0_loc_channel_dout),
    .if_empty_n(mat_RES_54_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_54_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_54_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_53_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_10),
    .if_full_n(mat_RES_53_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_53_0_loc_channel_dout),
    .if_empty_n(mat_RES_53_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_53_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_53_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_52_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_11),
    .if_full_n(mat_RES_52_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_52_0_loc_channel_dout),
    .if_empty_n(mat_RES_52_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_52_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_52_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_51_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_12),
    .if_full_n(mat_RES_51_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_51_0_loc_channel_dout),
    .if_empty_n(mat_RES_51_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_51_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_51_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_50_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_13),
    .if_full_n(mat_RES_50_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_50_0_loc_channel_dout),
    .if_empty_n(mat_RES_50_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_50_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_50_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_49_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_14),
    .if_full_n(mat_RES_49_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_49_0_loc_channel_dout),
    .if_empty_n(mat_RES_49_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_49_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_49_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_48_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_15),
    .if_full_n(mat_RES_48_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_48_0_loc_channel_dout),
    .if_empty_n(mat_RES_48_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_48_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_48_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_47_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_16),
    .if_full_n(mat_RES_47_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_47_0_loc_channel_dout),
    .if_empty_n(mat_RES_47_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_47_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_47_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_46_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_17),
    .if_full_n(mat_RES_46_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_46_0_loc_channel_dout),
    .if_empty_n(mat_RES_46_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_46_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_46_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_45_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_18),
    .if_full_n(mat_RES_45_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_45_0_loc_channel_dout),
    .if_empty_n(mat_RES_45_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_45_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_45_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_44_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_19),
    .if_full_n(mat_RES_44_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_44_0_loc_channel_dout),
    .if_empty_n(mat_RES_44_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_44_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_44_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_43_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_20),
    .if_full_n(mat_RES_43_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_43_0_loc_channel_dout),
    .if_empty_n(mat_RES_43_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_43_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_43_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_42_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_21),
    .if_full_n(mat_RES_42_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_42_0_loc_channel_dout),
    .if_empty_n(mat_RES_42_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_42_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_42_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_41_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_22),
    .if_full_n(mat_RES_41_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_41_0_loc_channel_dout),
    .if_empty_n(mat_RES_41_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_41_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_41_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_40_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_23),
    .if_full_n(mat_RES_40_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_40_0_loc_channel_dout),
    .if_empty_n(mat_RES_40_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_40_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_40_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_39_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_24),
    .if_full_n(mat_RES_39_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_39_0_loc_channel_dout),
    .if_empty_n(mat_RES_39_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_39_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_39_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_38_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_25),
    .if_full_n(mat_RES_38_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_38_0_loc_channel_dout),
    .if_empty_n(mat_RES_38_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_38_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_38_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_37_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_26),
    .if_full_n(mat_RES_37_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_37_0_loc_channel_dout),
    .if_empty_n(mat_RES_37_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_37_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_37_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_36_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_27),
    .if_full_n(mat_RES_36_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_36_0_loc_channel_dout),
    .if_empty_n(mat_RES_36_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_36_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_36_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_35_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_28),
    .if_full_n(mat_RES_35_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_35_0_loc_channel_dout),
    .if_empty_n(mat_RES_35_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_35_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_35_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_34_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_29),
    .if_full_n(mat_RES_34_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_34_0_loc_channel_dout),
    .if_empty_n(mat_RES_34_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_34_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_34_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_33_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_30),
    .if_full_n(mat_RES_33_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_33_0_loc_channel_dout),
    .if_empty_n(mat_RES_33_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_33_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_33_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_32_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_31),
    .if_full_n(mat_RES_32_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_32_0_loc_channel_dout),
    .if_empty_n(mat_RES_32_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_32_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_32_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_31_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_32),
    .if_full_n(mat_RES_31_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_31_0_loc_channel_dout),
    .if_empty_n(mat_RES_31_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_31_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_31_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_30_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_33),
    .if_full_n(mat_RES_30_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_30_0_loc_channel_dout),
    .if_empty_n(mat_RES_30_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_30_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_30_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_29_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_34),
    .if_full_n(mat_RES_29_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_29_0_loc_channel_dout),
    .if_empty_n(mat_RES_29_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_29_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_29_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_28_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_35),
    .if_full_n(mat_RES_28_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_28_0_loc_channel_dout),
    .if_empty_n(mat_RES_28_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_28_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_28_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_27_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_36),
    .if_full_n(mat_RES_27_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_27_0_loc_channel_dout),
    .if_empty_n(mat_RES_27_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_27_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_27_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_26_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_37),
    .if_full_n(mat_RES_26_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_26_0_loc_channel_dout),
    .if_empty_n(mat_RES_26_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_26_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_26_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_25_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_38),
    .if_full_n(mat_RES_25_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_25_0_loc_channel_dout),
    .if_empty_n(mat_RES_25_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_25_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_25_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_24_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_39),
    .if_full_n(mat_RES_24_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_24_0_loc_channel_dout),
    .if_empty_n(mat_RES_24_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_24_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_24_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_23_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_40),
    .if_full_n(mat_RES_23_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_23_0_loc_channel_dout),
    .if_empty_n(mat_RES_23_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_23_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_23_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_22_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_41),
    .if_full_n(mat_RES_22_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_22_0_loc_channel_dout),
    .if_empty_n(mat_RES_22_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_22_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_22_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_21_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_42),
    .if_full_n(mat_RES_21_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_21_0_loc_channel_dout),
    .if_empty_n(mat_RES_21_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_21_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_21_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_20_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_43),
    .if_full_n(mat_RES_20_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_20_0_loc_channel_dout),
    .if_empty_n(mat_RES_20_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_20_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_20_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_19_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_44),
    .if_full_n(mat_RES_19_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_19_0_loc_channel_dout),
    .if_empty_n(mat_RES_19_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_19_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_19_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_18_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_45),
    .if_full_n(mat_RES_18_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_18_0_loc_channel_dout),
    .if_empty_n(mat_RES_18_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_18_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_18_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_17_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_46),
    .if_full_n(mat_RES_17_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_17_0_loc_channel_dout),
    .if_empty_n(mat_RES_17_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_17_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_17_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_16_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_47),
    .if_full_n(mat_RES_16_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_16_0_loc_channel_dout),
    .if_empty_n(mat_RES_16_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_16_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_16_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_15_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_48),
    .if_full_n(mat_RES_15_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_15_0_loc_channel_dout),
    .if_empty_n(mat_RES_15_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_15_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_15_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_14_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_49),
    .if_full_n(mat_RES_14_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_14_0_loc_channel_dout),
    .if_empty_n(mat_RES_14_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_14_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_14_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_13_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_50),
    .if_full_n(mat_RES_13_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_13_0_loc_channel_dout),
    .if_empty_n(mat_RES_13_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_13_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_13_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_12_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_51),
    .if_full_n(mat_RES_12_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_12_0_loc_channel_dout),
    .if_empty_n(mat_RES_12_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_12_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_12_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_11_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_52),
    .if_full_n(mat_RES_11_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_11_0_loc_channel_dout),
    .if_empty_n(mat_RES_11_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_11_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_11_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_10_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_53),
    .if_full_n(mat_RES_10_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_10_0_loc_channel_dout),
    .if_empty_n(mat_RES_10_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_10_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_10_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_9_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_54),
    .if_full_n(mat_RES_9_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_9_0_loc_channel_dout),
    .if_empty_n(mat_RES_9_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_9_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_9_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_8_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_55),
    .if_full_n(mat_RES_8_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_8_0_loc_channel_dout),
    .if_empty_n(mat_RES_8_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_8_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_8_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_7_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_56),
    .if_full_n(mat_RES_7_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_7_0_loc_channel_dout),
    .if_empty_n(mat_RES_7_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_7_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_7_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_6_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_57),
    .if_full_n(mat_RES_6_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_6_0_loc_channel_dout),
    .if_empty_n(mat_RES_6_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_6_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_6_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_5_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_58),
    .if_full_n(mat_RES_5_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_5_0_loc_channel_dout),
    .if_empty_n(mat_RES_5_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_5_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_5_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_4_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_59),
    .if_full_n(mat_RES_4_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_4_0_loc_channel_dout),
    .if_empty_n(mat_RES_4_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_4_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_4_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_3_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_60),
    .if_full_n(mat_RES_3_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_3_0_loc_channel_dout),
    .if_empty_n(mat_RES_3_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_3_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_3_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_2_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_61),
    .if_full_n(mat_RES_2_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_2_0_loc_channel_dout),
    .if_empty_n(mat_RES_2_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_2_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_2_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_1_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_62),
    .if_full_n(mat_RES_1_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_1_0_loc_channel_dout),
    .if_empty_n(mat_RES_1_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_1_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_1_0_loc_channel_fifo_cap)
);

myip_v2_0_HLS_fifo_w32_d2_S mat_RES_0_0_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_myip_v2_0_HLS_compute_proc_U0_ap_return_63),
    .if_full_n(mat_RES_0_0_loc_channel_full_n),
    .if_write(ap_channel_done_mat_RES_0_0_loc_channel),
    .if_dout(mat_RES_0_0_loc_channel_dout),
    .if_empty_n(mat_RES_0_0_loc_channel_empty_n),
    .if_read(Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_ready),
    .if_num_data_valid(mat_RES_0_0_loc_channel_num_data_valid),
    .if_fifo_cap(mat_RES_0_0_loc_channel_fifo_cap)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_mat_A <= 1'b0;
    end else begin
        if (((Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_done & Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_mat_A <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_mat_A <= ap_sync_channel_write_mat_A;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_mat_RES_0_0_loc_channel <= 1'b0;
    end else begin
        if (((Loop_myip_v2_0_HLS_compute_proc_U0_ap_done & Loop_myip_v2_0_HLS_compute_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_mat_RES_0_0_loc_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_mat_RES_0_0_loc_channel <= ap_sync_channel_write_mat_RES_0_0_loc_channel;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_p_loc24_channel <= 1'b0;
    end else begin
        if (((Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_done & Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_p_loc24_channel <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_p_loc24_channel <= ap_sync_channel_write_p_loc24_channel;
        end
    end
end

assign Loop_myip_v2_0_HLS_compute_proc_U0_ap_continue = ap_sync_channel_write_mat_RES_0_0_loc_channel;

assign Loop_myip_v2_0_HLS_compute_proc_U0_ap_start = p_loc_channel_empty_n;

assign Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_continue = ap_sync_channel_write_mat_A;

assign Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_start = 1'b1;

assign Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_full_n = mat_A_i_full_n;

assign Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_continue = 1'b1;

assign Loop_myip_v2_0_HLS_write_outputs_proc_U0_ap_start = mat_RES_63_0_loc_channel_empty_n;

assign M_AXIS_TDATA = Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TDATA;

assign M_AXIS_TKEEP = Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TKEEP;

assign M_AXIS_TLAST = Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TLAST;

assign M_AXIS_TSTRB = Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TSTRB;

assign M_AXIS_TVALID = Loop_myip_v2_0_HLS_write_outputs_proc_U0_M_AXIS_TVALID;

assign S_AXIS_TREADY = Loop_myip_v2_0_HLS_read_inputs_proc_U0_S_AXIS_TREADY;

assign ap_channel_done_mat_A = ((ap_sync_reg_channel_write_mat_A ^ 1'b1) & Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_done);

assign ap_channel_done_mat_RES_0_0_loc_channel = ((ap_sync_reg_channel_write_mat_RES_0_0_loc_channel ^ 1'b1) & Loop_myip_v2_0_HLS_compute_proc_U0_ap_done);

assign ap_channel_done_p_loc24_channel = ((ap_sync_reg_channel_write_p_loc24_channel ^ 1'b1) & Loop_myip_v2_0_HLS_read_inputs_proc_U0_ap_done);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_channel_write_mat_A = ((ap_channel_done_mat_A & Loop_myip_v2_0_HLS_read_inputs_proc_U0_mat_A_0_full_n) | ap_sync_reg_channel_write_mat_A);

assign ap_sync_channel_write_mat_RES_0_0_loc_channel = ((mat_RES_0_0_loc_channel_full_n & ap_channel_done_mat_RES_0_0_loc_channel) | ap_sync_reg_channel_write_mat_RES_0_0_loc_channel);

assign ap_sync_channel_write_p_loc24_channel = ((p_loc24_channel_full_n & ap_channel_done_p_loc24_channel) | ap_sync_reg_channel_write_p_loc24_channel);

endmodule //myip_v2_0_HLS
