// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myip_v2_0_HLS_Loop_myip_v2_0_HLS_write_outputs_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        M_AXIS_TREADY,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        p_read10,
        p_read11,
        p_read12,
        p_read13,
        p_read14,
        p_read15,
        p_read16,
        p_read17,
        p_read18,
        p_read19,
        p_read20,
        p_read21,
        p_read22,
        p_read23,
        p_read24,
        p_read25,
        p_read26,
        p_read27,
        p_read28,
        p_read29,
        p_read30,
        p_read31,
        p_read32,
        p_read33,
        p_read34,
        p_read35,
        p_read36,
        p_read37,
        p_read38,
        p_read39,
        p_read40,
        p_read41,
        p_read42,
        p_read43,
        p_read44,
        p_read45,
        p_read46,
        p_read47,
        p_read48,
        p_read49,
        p_read50,
        p_read51,
        p_read52,
        p_read53,
        p_read54,
        p_read55,
        p_read56,
        p_read57,
        p_read58,
        p_read59,
        p_read60,
        p_read61,
        p_read62,
        p_read63,
        M_AXIS_TDATA,
        M_AXIS_TVALID,
        M_AXIS_TKEEP,
        M_AXIS_TSTRB,
        M_AXIS_TLAST
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_state2 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   M_AXIS_TREADY;
input  [31:0] p_read;
input  [31:0] p_read1;
input  [31:0] p_read2;
input  [31:0] p_read3;
input  [31:0] p_read4;
input  [31:0] p_read5;
input  [31:0] p_read6;
input  [31:0] p_read7;
input  [31:0] p_read8;
input  [31:0] p_read9;
input  [31:0] p_read10;
input  [31:0] p_read11;
input  [31:0] p_read12;
input  [31:0] p_read13;
input  [31:0] p_read14;
input  [31:0] p_read15;
input  [31:0] p_read16;
input  [31:0] p_read17;
input  [31:0] p_read18;
input  [31:0] p_read19;
input  [31:0] p_read20;
input  [31:0] p_read21;
input  [31:0] p_read22;
input  [31:0] p_read23;
input  [31:0] p_read24;
input  [31:0] p_read25;
input  [31:0] p_read26;
input  [31:0] p_read27;
input  [31:0] p_read28;
input  [31:0] p_read29;
input  [31:0] p_read30;
input  [31:0] p_read31;
input  [31:0] p_read32;
input  [31:0] p_read33;
input  [31:0] p_read34;
input  [31:0] p_read35;
input  [31:0] p_read36;
input  [31:0] p_read37;
input  [31:0] p_read38;
input  [31:0] p_read39;
input  [31:0] p_read40;
input  [31:0] p_read41;
input  [31:0] p_read42;
input  [31:0] p_read43;
input  [31:0] p_read44;
input  [31:0] p_read45;
input  [31:0] p_read46;
input  [31:0] p_read47;
input  [31:0] p_read48;
input  [31:0] p_read49;
input  [31:0] p_read50;
input  [31:0] p_read51;
input  [31:0] p_read52;
input  [31:0] p_read53;
input  [31:0] p_read54;
input  [31:0] p_read55;
input  [31:0] p_read56;
input  [31:0] p_read57;
input  [31:0] p_read58;
input  [31:0] p_read59;
input  [31:0] p_read60;
input  [31:0] p_read61;
input  [31:0] p_read62;
input  [31:0] p_read63;
output  [31:0] M_AXIS_TDATA;
output   M_AXIS_TVALID;
output  [3:0] M_AXIS_TKEEP;
output  [3:0] M_AXIS_TSTRB;
output  [0:0] M_AXIS_TLAST;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state2;
wire    regslice_both_M_AXIS_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage1_iter0;
reg   [0:0] icmp_ln90_reg_1017;
reg    ap_condition_exit_pp0_iter0_stage1;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    M_AXIS_TDATA_blk_n;
reg    ap_done_reg;
wire   [31:0] tmp_fu_722_p131;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln90_fu_987_p2;
reg   [5:0] word_cnt_fu_308;
wire   [5:0] word_cnt_3_fu_994_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_word_cnt_1;
wire   [31:0] tmp_fu_722_p129;
wire    ap_continue_int;
reg    ap_done_int;
reg   [1:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    M_AXIS_TVALID_int_regslice;
wire    M_AXIS_TREADY_int_regslice;
wire    regslice_both_M_AXIS_V_data_V_U_vld_out;
wire    regslice_both_M_AXIS_V_keep_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_M_AXIS_V_strb_V_U_apdone_blk;
wire    regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_M_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] M_AXIS_TLAST_int_regslice;
wire    regslice_both_M_AXIS_V_last_V_U_ack_in_dummy;
wire    regslice_both_M_AXIS_V_last_V_U_vld_out;
wire   [5:0] tmp_fu_722_p1;
wire   [5:0] tmp_fu_722_p3;
wire   [5:0] tmp_fu_722_p5;
wire   [5:0] tmp_fu_722_p7;
wire   [5:0] tmp_fu_722_p9;
wire   [5:0] tmp_fu_722_p11;
wire   [5:0] tmp_fu_722_p13;
wire   [5:0] tmp_fu_722_p15;
wire   [5:0] tmp_fu_722_p17;
wire   [5:0] tmp_fu_722_p19;
wire   [5:0] tmp_fu_722_p21;
wire   [5:0] tmp_fu_722_p23;
wire   [5:0] tmp_fu_722_p25;
wire   [5:0] tmp_fu_722_p27;
wire   [5:0] tmp_fu_722_p29;
wire   [5:0] tmp_fu_722_p31;
wire   [5:0] tmp_fu_722_p33;
wire   [5:0] tmp_fu_722_p35;
wire   [5:0] tmp_fu_722_p37;
wire   [5:0] tmp_fu_722_p39;
wire   [5:0] tmp_fu_722_p41;
wire   [5:0] tmp_fu_722_p43;
wire   [5:0] tmp_fu_722_p45;
wire   [5:0] tmp_fu_722_p47;
wire   [5:0] tmp_fu_722_p49;
wire   [5:0] tmp_fu_722_p51;
wire   [5:0] tmp_fu_722_p53;
wire   [5:0] tmp_fu_722_p55;
wire   [5:0] tmp_fu_722_p57;
wire   [5:0] tmp_fu_722_p59;
wire   [5:0] tmp_fu_722_p61;
wire   [5:0] tmp_fu_722_p63;
wire  signed [5:0] tmp_fu_722_p65;
wire  signed [5:0] tmp_fu_722_p67;
wire  signed [5:0] tmp_fu_722_p69;
wire  signed [5:0] tmp_fu_722_p71;
wire  signed [5:0] tmp_fu_722_p73;
wire  signed [5:0] tmp_fu_722_p75;
wire  signed [5:0] tmp_fu_722_p77;
wire  signed [5:0] tmp_fu_722_p79;
wire  signed [5:0] tmp_fu_722_p81;
wire  signed [5:0] tmp_fu_722_p83;
wire  signed [5:0] tmp_fu_722_p85;
wire  signed [5:0] tmp_fu_722_p87;
wire  signed [5:0] tmp_fu_722_p89;
wire  signed [5:0] tmp_fu_722_p91;
wire  signed [5:0] tmp_fu_722_p93;
wire  signed [5:0] tmp_fu_722_p95;
wire  signed [5:0] tmp_fu_722_p97;
wire  signed [5:0] tmp_fu_722_p99;
wire  signed [5:0] tmp_fu_722_p101;
wire  signed [5:0] tmp_fu_722_p103;
wire  signed [5:0] tmp_fu_722_p105;
wire  signed [5:0] tmp_fu_722_p107;
wire  signed [5:0] tmp_fu_722_p109;
wire  signed [5:0] tmp_fu_722_p111;
wire  signed [5:0] tmp_fu_722_p113;
wire  signed [5:0] tmp_fu_722_p115;
wire  signed [5:0] tmp_fu_722_p117;
wire  signed [5:0] tmp_fu_722_p119;
wire  signed [5:0] tmp_fu_722_p121;
wire  signed [5:0] tmp_fu_722_p123;
wire  signed [5:0] tmp_fu_722_p125;
wire  signed [5:0] tmp_fu_722_p127;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 word_cnt_fu_308 = 6'd0;
end

(* dissolve_hierarchy = "yes" *) myip_v2_0_HLS_sparsemux_129_6_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 6'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 6'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 6'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 6'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 6'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 6'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 6'h7 ),
    .din7_WIDTH( 32 ),
    .CASE8( 6'h8 ),
    .din8_WIDTH( 32 ),
    .CASE9( 6'h9 ),
    .din9_WIDTH( 32 ),
    .CASE10( 6'hA ),
    .din10_WIDTH( 32 ),
    .CASE11( 6'hB ),
    .din11_WIDTH( 32 ),
    .CASE12( 6'hC ),
    .din12_WIDTH( 32 ),
    .CASE13( 6'hD ),
    .din13_WIDTH( 32 ),
    .CASE14( 6'hE ),
    .din14_WIDTH( 32 ),
    .CASE15( 6'hF ),
    .din15_WIDTH( 32 ),
    .CASE16( 6'h10 ),
    .din16_WIDTH( 32 ),
    .CASE17( 6'h11 ),
    .din17_WIDTH( 32 ),
    .CASE18( 6'h12 ),
    .din18_WIDTH( 32 ),
    .CASE19( 6'h13 ),
    .din19_WIDTH( 32 ),
    .CASE20( 6'h14 ),
    .din20_WIDTH( 32 ),
    .CASE21( 6'h15 ),
    .din21_WIDTH( 32 ),
    .CASE22( 6'h16 ),
    .din22_WIDTH( 32 ),
    .CASE23( 6'h17 ),
    .din23_WIDTH( 32 ),
    .CASE24( 6'h18 ),
    .din24_WIDTH( 32 ),
    .CASE25( 6'h19 ),
    .din25_WIDTH( 32 ),
    .CASE26( 6'h1A ),
    .din26_WIDTH( 32 ),
    .CASE27( 6'h1B ),
    .din27_WIDTH( 32 ),
    .CASE28( 6'h1C ),
    .din28_WIDTH( 32 ),
    .CASE29( 6'h1D ),
    .din29_WIDTH( 32 ),
    .CASE30( 6'h1E ),
    .din30_WIDTH( 32 ),
    .CASE31( 6'h1F ),
    .din31_WIDTH( 32 ),
    .CASE32( 6'h20 ),
    .din32_WIDTH( 32 ),
    .CASE33( 6'h21 ),
    .din33_WIDTH( 32 ),
    .CASE34( 6'h22 ),
    .din34_WIDTH( 32 ),
    .CASE35( 6'h23 ),
    .din35_WIDTH( 32 ),
    .CASE36( 6'h24 ),
    .din36_WIDTH( 32 ),
    .CASE37( 6'h25 ),
    .din37_WIDTH( 32 ),
    .CASE38( 6'h26 ),
    .din38_WIDTH( 32 ),
    .CASE39( 6'h27 ),
    .din39_WIDTH( 32 ),
    .CASE40( 6'h28 ),
    .din40_WIDTH( 32 ),
    .CASE41( 6'h29 ),
    .din41_WIDTH( 32 ),
    .CASE42( 6'h2A ),
    .din42_WIDTH( 32 ),
    .CASE43( 6'h2B ),
    .din43_WIDTH( 32 ),
    .CASE44( 6'h2C ),
    .din44_WIDTH( 32 ),
    .CASE45( 6'h2D ),
    .din45_WIDTH( 32 ),
    .CASE46( 6'h2E ),
    .din46_WIDTH( 32 ),
    .CASE47( 6'h2F ),
    .din47_WIDTH( 32 ),
    .CASE48( 6'h30 ),
    .din48_WIDTH( 32 ),
    .CASE49( 6'h31 ),
    .din49_WIDTH( 32 ),
    .CASE50( 6'h32 ),
    .din50_WIDTH( 32 ),
    .CASE51( 6'h33 ),
    .din51_WIDTH( 32 ),
    .CASE52( 6'h34 ),
    .din52_WIDTH( 32 ),
    .CASE53( 6'h35 ),
    .din53_WIDTH( 32 ),
    .CASE54( 6'h36 ),
    .din54_WIDTH( 32 ),
    .CASE55( 6'h37 ),
    .din55_WIDTH( 32 ),
    .CASE56( 6'h38 ),
    .din56_WIDTH( 32 ),
    .CASE57( 6'h39 ),
    .din57_WIDTH( 32 ),
    .CASE58( 6'h3A ),
    .din58_WIDTH( 32 ),
    .CASE59( 6'h3B ),
    .din59_WIDTH( 32 ),
    .CASE60( 6'h3C ),
    .din60_WIDTH( 32 ),
    .CASE61( 6'h3D ),
    .din61_WIDTH( 32 ),
    .CASE62( 6'h3E ),
    .din62_WIDTH( 32 ),
    .CASE63( 6'h3F ),
    .din63_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
sparsemux_129_6_32_1_1_U38(
    .din0(p_read),
    .din1(p_read1),
    .din2(p_read2),
    .din3(p_read3),
    .din4(p_read4),
    .din5(p_read5),
    .din6(p_read6),
    .din7(p_read7),
    .din8(p_read8),
    .din9(p_read9),
    .din10(p_read10),
    .din11(p_read11),
    .din12(p_read12),
    .din13(p_read13),
    .din14(p_read14),
    .din15(p_read15),
    .din16(p_read16),
    .din17(p_read17),
    .din18(p_read18),
    .din19(p_read19),
    .din20(p_read20),
    .din21(p_read21),
    .din22(p_read22),
    .din23(p_read23),
    .din24(p_read24),
    .din25(p_read25),
    .din26(p_read26),
    .din27(p_read27),
    .din28(p_read28),
    .din29(p_read29),
    .din30(p_read30),
    .din31(p_read31),
    .din32(p_read32),
    .din33(p_read33),
    .din34(p_read34),
    .din35(p_read35),
    .din36(p_read36),
    .din37(p_read37),
    .din38(p_read38),
    .din39(p_read39),
    .din40(p_read40),
    .din41(p_read41),
    .din42(p_read42),
    .din43(p_read43),
    .din44(p_read44),
    .din45(p_read45),
    .din46(p_read46),
    .din47(p_read47),
    .din48(p_read48),
    .din49(p_read49),
    .din50(p_read50),
    .din51(p_read51),
    .din52(p_read52),
    .din53(p_read53),
    .din54(p_read54),
    .din55(p_read55),
    .din56(p_read56),
    .din57(p_read57),
    .din58(p_read58),
    .din59(p_read59),
    .din60(p_read60),
    .din61(p_read61),
    .din62(p_read62),
    .din63(p_read63),
    .def(tmp_fu_722_p129),
    .sel(ap_sig_allocacmp_word_cnt_1),
    .dout(tmp_fu_722_p131)
);

myip_v2_0_HLS_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage1),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_M_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tmp_fu_722_p131),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(M_AXIS_TREADY_int_regslice),
    .data_out(M_AXIS_TDATA),
    .vld_out(regslice_both_M_AXIS_V_data_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(4'd15),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy),
    .data_out(M_AXIS_TKEEP),
    .vld_out(regslice_both_M_AXIS_V_keep_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_keep_V_U_apdone_blk)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_M_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(4'd15),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy),
    .data_out(M_AXIS_TSTRB),
    .vld_out(regslice_both_M_AXIS_V_strb_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_strb_V_U_apdone_blk)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_M_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(M_AXIS_TLAST_int_regslice),
    .vld_in(M_AXIS_TVALID_int_regslice),
    .ack_in(regslice_both_M_AXIS_V_last_V_U_ack_in_dummy),
    .data_out(M_AXIS_TLAST),
    .vld_out(regslice_both_M_AXIS_V_last_V_U_vld_out),
    .ack_out(M_AXIS_TREADY),
    .apdone_blk(regslice_both_M_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        word_cnt_fu_308 <= word_cnt_3_fu_994_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        icmp_ln90_reg_1017 <= icmp_ln90_fu_987_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | (~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1)))) begin
        M_AXIS_TDATA_blk_n = M_AXIS_TREADY_int_regslice;
    end else begin
        M_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        M_AXIS_TVALID_int_regslice = 1'b1;
    end else begin
        M_AXIS_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage1_iter0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln90_reg_1017 == 1'd1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_word_cnt_1 = 6'd0;
    end else begin
        ap_sig_allocacmp_word_cnt_1 = word_cnt_fu_308;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage1_iter0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign M_AXIS_TLAST_int_regslice = ((ap_sig_allocacmp_word_cnt_1 == 6'd63) ? 1'b1 : 1'b0);

assign M_AXIS_TVALID = regslice_both_M_AXIS_V_data_V_U_vld_out;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (1'b0 == M_AXIS_TREADY_int_regslice) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = ((regslice_both_M_AXIS_V_data_V_U_apdone_blk == 1'b1) | (1'b0 == M_AXIS_TREADY_int_regslice));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage1;

assign ap_ready = ap_ready_sig;

assign icmp_ln90_fu_987_p2 = ((ap_sig_allocacmp_word_cnt_1 == 6'd63) ? 1'b1 : 1'b0);

assign tmp_fu_722_p129 = 'bx;

assign word_cnt_3_fu_994_p2 = (ap_sig_allocacmp_word_cnt_1 + 6'd1);

endmodule //myip_v2_0_HLS_Loop_myip_v2_0_HLS_write_outputs_proc
