-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myip_v2_0_HLS_Loop_myip_v2_0_HLS_read_inputs_proc is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    S_AXIS_TVALID : IN STD_LOGIC;
    mat_A_7_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_7_ce0 : OUT STD_LOGIC;
    mat_A_7_we0 : OUT STD_LOGIC;
    mat_A_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_A_6_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_6_ce0 : OUT STD_LOGIC;
    mat_A_6_we0 : OUT STD_LOGIC;
    mat_A_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_A_5_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_5_ce0 : OUT STD_LOGIC;
    mat_A_5_we0 : OUT STD_LOGIC;
    mat_A_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_A_4_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_4_ce0 : OUT STD_LOGIC;
    mat_A_4_we0 : OUT STD_LOGIC;
    mat_A_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_A_3_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_3_ce0 : OUT STD_LOGIC;
    mat_A_3_we0 : OUT STD_LOGIC;
    mat_A_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_A_2_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_2_ce0 : OUT STD_LOGIC;
    mat_A_2_we0 : OUT STD_LOGIC;
    mat_A_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_A_1_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_1_ce0 : OUT STD_LOGIC;
    mat_A_1_we0 : OUT STD_LOGIC;
    mat_A_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    mat_A_0_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    mat_A_0_ce0 : OUT STD_LOGIC;
    mat_A_0_we0 : OUT STD_LOGIC;
    mat_A_0_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    S_AXIS_TREADY : OUT STD_LOGIC;
    S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of myip_v2_0_HLS_Loop_myip_v2_0_HLS_read_inputs_proc is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv10_207 : STD_LOGIC_VECTOR (9 downto 0) := "1000000111";
    constant ap_const_lv10_206 : STD_LOGIC_VECTOR (9 downto 0) := "1000000110";
    constant ap_const_lv10_205 : STD_LOGIC_VECTOR (9 downto 0) := "1000000101";
    constant ap_const_lv10_204 : STD_LOGIC_VECTOR (9 downto 0) := "1000000100";
    constant ap_const_lv10_203 : STD_LOGIC_VECTOR (9 downto 0) := "1000000011";
    constant ap_const_lv10_202 : STD_LOGIC_VECTOR (9 downto 0) := "1000000010";
    constant ap_const_lv10_201 : STD_LOGIC_VECTOR (9 downto 0) := "1000000001";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln50_fu_394_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal S_AXIS_TDATA_blk_n : STD_LOGIC;
    signal zext_ln54_fu_280_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_304_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal word_cnt61_fu_106 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal word_cnt_5_fu_312_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_word_cnt : STD_LOGIC_VECTOR (9 downto 0);
    signal word_cnt_load_fu_263_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_out_046_fu_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_sig_allocacmp_p_out_046_load : STD_LOGIC_VECTOR (31 downto 0);
    signal p_out16_048_fu_114 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_out2_050_fu_118 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_out3_052_fu_122 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_out4_054_fu_126 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_out5_056_fu_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_out6_058_fu_134 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal p_out7_060_fu_138 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal mat_A_6_we0_local : STD_LOGIC;
    signal trunc_ln50_fu_266_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal mat_A_6_ce0_local : STD_LOGIC;
    signal mat_A_5_we0_local : STD_LOGIC;
    signal mat_A_5_ce0_local : STD_LOGIC;
    signal mat_A_4_we0_local : STD_LOGIC;
    signal mat_A_4_ce0_local : STD_LOGIC;
    signal mat_A_3_we0_local : STD_LOGIC;
    signal mat_A_3_ce0_local : STD_LOGIC;
    signal mat_A_2_we0_local : STD_LOGIC;
    signal mat_A_2_ce0_local : STD_LOGIC;
    signal mat_A_1_we0_local : STD_LOGIC;
    signal mat_A_1_ce0_local : STD_LOGIC;
    signal mat_A_0_we0_local : STD_LOGIC;
    signal mat_A_0_ce0_local : STD_LOGIC;
    signal mat_A_7_we0_local : STD_LOGIC;
    signal mat_A_7_ce0_local : STD_LOGIC;
    signal lshr_ln_fu_270_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_return_0_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_1_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_2_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_3_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_4_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_5_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_6_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_return_7_preg : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal regslice_both_S_AXIS_V_data_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal S_AXIS_TVALID_int_regslice : STD_LOGIC;
    signal S_AXIS_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_S_AXIS_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_S_AXIS_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_ack_in : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myip_v2_0_HLS_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;


    component myip_v2_0_HLS_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component myip_v2_0_HLS_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);

    regslice_both_S_AXIS_V_data_V_U : component myip_v2_0_HLS_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => S_AXIS_TDATA,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_data_V_U_ack_in,
        data_out => S_AXIS_TDATA_int_regslice,
        vld_out => S_AXIS_TVALID_int_regslice,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_data_V_U_apdone_blk);

    regslice_both_S_AXIS_V_keep_V_U : component myip_v2_0_HLS_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => S_AXIS_TKEEP,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_keep_V_U_ack_in,
        data_out => S_AXIS_TKEEP_int_regslice,
        vld_out => regslice_both_S_AXIS_V_keep_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_keep_V_U_apdone_blk);

    regslice_both_S_AXIS_V_strb_V_U : component myip_v2_0_HLS_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => S_AXIS_TSTRB,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_strb_V_U_ack_in,
        data_out => S_AXIS_TSTRB_int_regslice,
        vld_out => regslice_both_S_AXIS_V_strb_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_strb_V_U_apdone_blk);

    regslice_both_S_AXIS_V_last_V_U : component myip_v2_0_HLS_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => S_AXIS_TLAST,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_last_V_U_ack_in,
        data_out => S_AXIS_TLAST_int_regslice,
        vld_out => regslice_both_S_AXIS_V_last_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_return_0_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_0_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_0_preg <= ap_sig_allocacmp_p_out_046_load;
                end if; 
            end if;
        end if;
    end process;


    ap_return_1_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_1_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_1_preg <= p_out16_048_fu_114;
                end if; 
            end if;
        end if;
    end process;


    ap_return_2_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_2_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_2_preg <= p_out2_050_fu_118;
                end if; 
            end if;
        end if;
    end process;


    ap_return_3_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_3_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_3_preg <= p_out3_052_fu_122;
                end if; 
            end if;
        end if;
    end process;


    ap_return_4_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_4_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_4_preg <= p_out4_054_fu_126;
                end if; 
            end if;
        end if;
    end process;


    ap_return_5_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_5_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_5_preg <= p_out5_056_fu_130;
                end if; 
            end if;
        end if;
    end process;


    ap_return_6_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_6_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_6_preg <= p_out6_058_fu_134;
                end if; 
            end if;
        end if;
    end process;


    ap_return_7_preg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_return_7_preg <= ap_const_lv32_0;
            else
                if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_return_7_preg <= p_out7_060_fu_138;
                end if; 
            end if;
        end if;
    end process;


    word_cnt61_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                word_cnt61_fu_106 <= word_cnt_5_fu_312_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_206) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out16_048_fu_114 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_205) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out2_050_fu_118 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_204) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out3_052_fu_122 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_203) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out4_054_fu_126 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_202) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out5_056_fu_130 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_201) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out6_058_fu_134 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((word_cnt_load_fu_263_p1 = ap_const_lv10_201)) and not((word_cnt_load_fu_263_p1 = ap_const_lv10_202)) and not((word_cnt_load_fu_263_p1 = ap_const_lv10_203)) and not((word_cnt_load_fu_263_p1 = ap_const_lv10_204)) and not((word_cnt_load_fu_263_p1 = ap_const_lv10_205)) and not((word_cnt_load_fu_263_p1 = ap_const_lv10_206)) and not((word_cnt_load_fu_263_p1 = ap_const_lv10_207)) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out7_060_fu_138 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_207) and (tmp_fu_304_p3 = ap_const_lv1_1))) then
                p_out_046_fu_110 <= S_AXIS_TDATA_int_regslice;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    S_AXIS_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, ap_done_reg, ap_start_int, S_AXIS_TVALID_int_regslice)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_AXIS_TDATA_blk_n <= S_AXIS_TVALID_int_regslice;
        else 
            S_AXIS_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    S_AXIS_TREADY <= regslice_both_S_AXIS_V_data_V_U_ack_in;

    S_AXIS_TREADY_int_regslice_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            S_AXIS_TREADY_int_regslice <= ap_const_logic_1;
        else 
            S_AXIS_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg, ap_start_int, S_AXIS_TVALID_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or (ap_const_logic_0 = S_AXIS_TVALID_int_regslice) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln50_fu_394_p2)
    begin
        if (((icmp_ln50_fu_394_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_return_0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_sig_allocacmp_p_out_046_load, ap_return_0_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_0 <= ap_sig_allocacmp_p_out_046_load;
        else 
            ap_return_0 <= ap_return_0_preg;
        end if; 
    end process;


    ap_return_1_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, p_out16_048_fu_114, ap_return_1_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_1 <= p_out16_048_fu_114;
        else 
            ap_return_1 <= ap_return_1_preg;
        end if; 
    end process;


    ap_return_2_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, p_out2_050_fu_118, ap_return_2_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_2 <= p_out2_050_fu_118;
        else 
            ap_return_2 <= ap_return_2_preg;
        end if; 
    end process;


    ap_return_3_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, p_out3_052_fu_122, ap_return_3_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_3 <= p_out3_052_fu_122;
        else 
            ap_return_3 <= ap_return_3_preg;
        end if; 
    end process;


    ap_return_4_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, p_out4_054_fu_126, ap_return_4_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_4 <= p_out4_054_fu_126;
        else 
            ap_return_4 <= ap_return_4_preg;
        end if; 
    end process;


    ap_return_5_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, p_out5_056_fu_130, ap_return_5_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_5 <= p_out5_056_fu_130;
        else 
            ap_return_5 <= ap_return_5_preg;
        end if; 
    end process;


    ap_return_6_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, p_out6_058_fu_134, ap_return_6_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_6 <= p_out6_058_fu_134;
        else 
            ap_return_6 <= ap_return_6_preg;
        end if; 
    end process;


    ap_return_7_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, p_out7_060_fu_138, ap_return_7_preg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_return_7 <= p_out7_060_fu_138;
        else 
            ap_return_7 <= ap_return_7_preg;
        end if; 
    end process;


    ap_sig_allocacmp_p_out_046_load_assign_proc : process(ap_CS_fsm_state1, tmp_fu_304_p3, word_cnt_load_fu_263_p1, p_out_046_fu_110, S_AXIS_TDATA_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (word_cnt_load_fu_263_p1 = ap_const_lv10_207) and (tmp_fu_304_p3 = ap_const_lv1_1))) then 
            ap_sig_allocacmp_p_out_046_load <= S_AXIS_TDATA_int_regslice;
        else 
            ap_sig_allocacmp_p_out_046_load <= p_out_046_fu_110;
        end if; 
    end process;


    ap_sig_allocacmp_word_cnt_assign_proc : process(ap_CS_fsm_state1, word_cnt61_fu_106, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_word_cnt <= ap_const_lv10_0;
        else 
            ap_sig_allocacmp_word_cnt <= word_cnt61_fu_106;
        end if; 
    end process;

    icmp_ln50_fu_394_p2 <= "1" when (ap_sig_allocacmp_word_cnt = ap_const_lv10_207) else "0";
    lshr_ln_fu_270_p4 <= ap_sig_allocacmp_word_cnt(8 downto 3);
    mat_A_0_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_0_ce0 <= mat_A_0_ce0_local;

    mat_A_0_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_0_ce0_local <= ap_const_logic_1;
        else 
            mat_A_0_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_0_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_0_we0 <= mat_A_0_we0_local;

    mat_A_0_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_0_we0_local <= ap_const_logic_1;
        else 
            mat_A_0_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_1_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_1_ce0 <= mat_A_1_ce0_local;

    mat_A_1_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_1_ce0_local <= ap_const_logic_1;
        else 
            mat_A_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_1_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_1_we0 <= mat_A_1_we0_local;

    mat_A_1_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_1_we0_local <= ap_const_logic_1;
        else 
            mat_A_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_2_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_2_ce0 <= mat_A_2_ce0_local;

    mat_A_2_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_2_ce0_local <= ap_const_logic_1;
        else 
            mat_A_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_2_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_2_we0 <= mat_A_2_we0_local;

    mat_A_2_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_2) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_2_we0_local <= ap_const_logic_1;
        else 
            mat_A_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_3_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_3_ce0 <= mat_A_3_ce0_local;

    mat_A_3_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_3_ce0_local <= ap_const_logic_1;
        else 
            mat_A_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_3_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_3_we0 <= mat_A_3_we0_local;

    mat_A_3_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_3) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_3_we0_local <= ap_const_logic_1;
        else 
            mat_A_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_4_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_4_ce0 <= mat_A_4_ce0_local;

    mat_A_4_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_4_ce0_local <= ap_const_logic_1;
        else 
            mat_A_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_4_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_4_we0 <= mat_A_4_we0_local;

    mat_A_4_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_4) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_4_we0_local <= ap_const_logic_1;
        else 
            mat_A_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_5_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_5_ce0 <= mat_A_5_ce0_local;

    mat_A_5_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_5_ce0_local <= ap_const_logic_1;
        else 
            mat_A_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_5_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_5_we0 <= mat_A_5_we0_local;

    mat_A_5_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_5) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_5_we0_local <= ap_const_logic_1;
        else 
            mat_A_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_6_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_6_ce0 <= mat_A_6_ce0_local;

    mat_A_6_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_6_ce0_local <= ap_const_logic_1;
        else 
            mat_A_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_6_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_6_we0 <= mat_A_6_we0_local;

    mat_A_6_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_6) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_6_we0_local <= ap_const_logic_1;
        else 
            mat_A_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_7_address0 <= zext_ln54_fu_280_p1(6 - 1 downto 0);
    mat_A_7_ce0 <= mat_A_7_ce0_local;

    mat_A_7_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            mat_A_7_ce0_local <= ap_const_logic_1;
        else 
            mat_A_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    mat_A_7_d0 <= S_AXIS_TDATA_int_regslice;
    mat_A_7_we0 <= mat_A_7_we0_local;

    mat_A_7_we0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, tmp_fu_304_p3, trunc_ln50_fu_266_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (trunc_ln50_fu_266_p1 = ap_const_lv3_7) and (ap_const_logic_1 = ap_CS_fsm_state1) and (tmp_fu_304_p3 = ap_const_lv1_0))) then 
            mat_A_7_we0_local <= ap_const_logic_1;
        else 
            mat_A_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_304_p3 <= ap_sig_allocacmp_word_cnt(9 downto 9);
    trunc_ln50_fu_266_p1 <= ap_sig_allocacmp_word_cnt(3 - 1 downto 0);
    word_cnt_5_fu_312_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_word_cnt) + unsigned(ap_const_lv10_1));
    word_cnt_load_fu_263_p1 <= ap_sig_allocacmp_word_cnt;
    zext_ln54_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_270_p4),64));
end behav;
