// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myip_v2_0_HLS_Loop_myip_v2_0_HLS_read_inputs_proc (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        S_AXIS_TVALID,
        mat_A_7_address0,
        mat_A_7_ce0,
        mat_A_7_we0,
        mat_A_7_d0,
        mat_A_6_address0,
        mat_A_6_ce0,
        mat_A_6_we0,
        mat_A_6_d0,
        mat_A_5_address0,
        mat_A_5_ce0,
        mat_A_5_we0,
        mat_A_5_d0,
        mat_A_4_address0,
        mat_A_4_ce0,
        mat_A_4_we0,
        mat_A_4_d0,
        mat_A_3_address0,
        mat_A_3_ce0,
        mat_A_3_we0,
        mat_A_3_d0,
        mat_A_2_address0,
        mat_A_2_ce0,
        mat_A_2_we0,
        mat_A_2_d0,
        mat_A_1_address0,
        mat_A_1_ce0,
        mat_A_1_we0,
        mat_A_1_d0,
        mat_A_0_address0,
        mat_A_0_ce0,
        mat_A_0_we0,
        mat_A_0_d0,
        S_AXIS_TDATA,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   S_AXIS_TVALID;
output  [5:0] mat_A_7_address0;
output   mat_A_7_ce0;
output   mat_A_7_we0;
output  [31:0] mat_A_7_d0;
output  [5:0] mat_A_6_address0;
output   mat_A_6_ce0;
output   mat_A_6_we0;
output  [31:0] mat_A_6_d0;
output  [5:0] mat_A_5_address0;
output   mat_A_5_ce0;
output   mat_A_5_we0;
output  [31:0] mat_A_5_d0;
output  [5:0] mat_A_4_address0;
output   mat_A_4_ce0;
output   mat_A_4_we0;
output  [31:0] mat_A_4_d0;
output  [5:0] mat_A_3_address0;
output   mat_A_3_ce0;
output   mat_A_3_we0;
output  [31:0] mat_A_3_d0;
output  [5:0] mat_A_2_address0;
output   mat_A_2_ce0;
output   mat_A_2_we0;
output  [31:0] mat_A_2_d0;
output  [5:0] mat_A_1_address0;
output   mat_A_1_ce0;
output   mat_A_1_we0;
output  [31:0] mat_A_1_d0;
output  [5:0] mat_A_0_address0;
output   mat_A_0_ce0;
output   mat_A_0_we0;
output  [31:0] mat_A_0_d0;
input  [31:0] S_AXIS_TDATA;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;

reg ap_idle;
reg[31:0] ap_return_0;
reg[31:0] ap_return_1;
reg[31:0] ap_return_2;
reg[31:0] ap_return_3;
reg[31:0] ap_return_4;
reg[31:0] ap_return_5;
reg[31:0] ap_return_6;
reg[31:0] ap_return_7;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_done_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln50_fu_392_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    S_AXIS_TDATA_blk_n;
wire   [63:0] zext_ln54_fu_278_p1;
wire   [0:0] tmp_fu_302_p3;
reg   [9:0] word_cnt61_fu_104;
wire   [9:0] word_cnt_5_fu_310_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_word_cnt;
wire   [9:0] word_cnt_load_fu_261_p1;
reg   [31:0] p_out_046_fu_108;
reg   [31:0] ap_sig_allocacmp_p_out_046_load;
reg   [31:0] p_out16_048_fu_112;
reg   [31:0] p_out2_050_fu_116;
reg   [31:0] p_out3_052_fu_120;
reg   [31:0] p_out4_054_fu_124;
reg   [31:0] p_out5_056_fu_128;
reg   [31:0] p_out6_058_fu_132;
reg   [31:0] p_out7_060_fu_136;
reg    mat_A_6_we0_local;
wire   [2:0] trunc_ln50_fu_264_p1;
reg    mat_A_6_ce0_local;
reg    mat_A_5_we0_local;
reg    mat_A_5_ce0_local;
reg    mat_A_4_we0_local;
reg    mat_A_4_ce0_local;
reg    mat_A_3_we0_local;
reg    mat_A_3_ce0_local;
reg    mat_A_2_we0_local;
reg    mat_A_2_ce0_local;
reg    mat_A_1_we0_local;
reg    mat_A_1_ce0_local;
reg    mat_A_0_we0_local;
reg    mat_A_0_ce0_local;
reg    mat_A_7_we0_local;
reg    mat_A_7_ce0_local;
wire   [5:0] lshr_ln_fu_268_p4;
reg   [31:0] ap_return_0_preg;
reg   [31:0] ap_return_1_preg;
reg   [31:0] ap_return_2_preg;
reg   [31:0] ap_return_3_preg;
reg   [31:0] ap_return_4_preg;
reg   [31:0] ap_return_5_preg;
reg   [31:0] ap_return_6_preg;
reg   [31:0] ap_return_7_preg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    regslice_both_S_AXIS_V_data_V_U_apdone_blk;
wire   [31:0] S_AXIS_TDATA_int_regslice;
wire    S_AXIS_TVALID_int_regslice;
reg    S_AXIS_TREADY_int_regslice;
wire    regslice_both_S_AXIS_V_data_V_U_ack_in;
wire    regslice_both_S_AXIS_V_keep_V_U_apdone_blk;
wire   [3:0] S_AXIS_TKEEP_int_regslice;
wire    regslice_both_S_AXIS_V_keep_V_U_vld_out;
wire    regslice_both_S_AXIS_V_keep_V_U_ack_in;
wire    regslice_both_S_AXIS_V_strb_V_U_apdone_blk;
wire   [3:0] S_AXIS_TSTRB_int_regslice;
wire    regslice_both_S_AXIS_V_strb_V_U_vld_out;
wire    regslice_both_S_AXIS_V_strb_V_U_ack_in;
wire    regslice_both_S_AXIS_V_last_V_U_apdone_blk;
wire   [0:0] S_AXIS_TLAST_int_regslice;
wire    regslice_both_S_AXIS_V_last_V_U_vld_out;
wire    regslice_both_S_AXIS_V_last_V_U_ack_in;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
#0 word_cnt61_fu_104 = 10'd0;
#0 p_out_046_fu_108 = 32'd0;
#0 p_out16_048_fu_112 = 32'd0;
#0 p_out2_050_fu_116 = 32'd0;
#0 p_out3_052_fu_120 = 32'd0;
#0 p_out4_054_fu_124 = 32'd0;
#0 p_out5_056_fu_128 = 32'd0;
#0 p_out6_058_fu_132 = 32'd0;
#0 p_out7_060_fu_136 = 32'd0;
#0 ap_return_0_preg = 32'd0;
#0 ap_return_1_preg = 32'd0;
#0 ap_return_2_preg = 32'd0;
#0 ap_return_3_preg = 32'd0;
#0 ap_return_4_preg = 32'd0;
#0 ap_return_5_preg = 32'd0;
#0 ap_return_6_preg = 32'd0;
#0 ap_return_7_preg = 32'd0;
end

myip_v2_0_HLS_flow_control_loop_pipe flow_control_loop_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(ap_continue)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 32 ))
regslice_both_S_AXIS_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(S_AXIS_TDATA),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_data_V_U_ack_in),
    .data_out(S_AXIS_TDATA_int_regslice),
    .vld_out(S_AXIS_TVALID_int_regslice),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_data_V_U_apdone_blk)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(S_AXIS_TKEEP),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_keep_V_U_ack_in),
    .data_out(S_AXIS_TKEEP_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_keep_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_keep_V_U_apdone_blk)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 4 ))
regslice_both_S_AXIS_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(S_AXIS_TSTRB),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_strb_V_U_ack_in),
    .data_out(S_AXIS_TSTRB_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_strb_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_strb_V_U_apdone_blk)
);

myip_v2_0_HLS_regslice_both #(
    .DataWidth( 1 ))
regslice_both_S_AXIS_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(S_AXIS_TLAST),
    .vld_in(S_AXIS_TVALID),
    .ack_in(regslice_both_S_AXIS_V_last_V_U_ack_in),
    .data_out(S_AXIS_TLAST_int_regslice),
    .vld_out(regslice_both_S_AXIS_V_last_V_U_vld_out),
    .ack_out(S_AXIS_TREADY_int_regslice),
    .apdone_blk(regslice_both_S_AXIS_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_0_preg <= ap_sig_allocacmp_p_out_046_load;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_1_preg <= p_out16_048_fu_112;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_2_preg <= p_out2_050_fu_116;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_3_preg <= p_out3_052_fu_120;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_4_preg <= p_out4_054_fu_124;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_5_preg <= p_out5_056_fu_128;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_6_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_6_preg <= p_out6_058_fu_132;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_7_preg <= 32'd0;
    end else begin
        if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_return_7_preg <= p_out7_060_fu_136;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        word_cnt61_fu_104 <= word_cnt_5_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd518) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out16_048_fu_112 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd517) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out2_050_fu_116 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd516) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out3_052_fu_120 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd515) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out4_054_fu_124 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd514) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out5_056_fu_128 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd513) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out6_058_fu_132 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~(word_cnt_load_fu_261_p1 == 10'd513) & ~(word_cnt_load_fu_261_p1 == 10'd514) & ~(word_cnt_load_fu_261_p1 == 10'd515) & ~(word_cnt_load_fu_261_p1 == 10'd516) & ~(word_cnt_load_fu_261_p1 == 10'd517) & ~(word_cnt_load_fu_261_p1 == 10'd518) & ~(word_cnt_load_fu_261_p1 == 10'd519) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out7_060_fu_136 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd519) & (tmp_fu_302_p3 == 1'd1))) begin
        p_out_046_fu_108 <= S_AXIS_TDATA_int_regslice;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        S_AXIS_TDATA_blk_n = S_AXIS_TVALID_int_regslice;
    end else begin
        S_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        S_AXIS_TREADY_int_regslice = 1'b1;
    end else begin
        S_AXIS_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln50_fu_392_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_0 = ap_sig_allocacmp_p_out_046_load;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_1 = p_out16_048_fu_112;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_2 = p_out2_050_fu_116;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_3 = p_out3_052_fu_120;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_4 = p_out4_054_fu_124;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_5 = p_out5_056_fu_128;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_6 = p_out6_058_fu_132;
    end else begin
        ap_return_6 = ap_return_6_preg;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_return_7 = p_out7_060_fu_136;
    end else begin
        ap_return_7 = ap_return_7_preg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (word_cnt_load_fu_261_p1 == 10'd519) & (tmp_fu_302_p3 == 1'd1))) begin
        ap_sig_allocacmp_p_out_046_load = S_AXIS_TDATA_int_regslice;
    end else begin
        ap_sig_allocacmp_p_out_046_load = p_out_046_fu_108;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_word_cnt = 10'd0;
    end else begin
        ap_sig_allocacmp_word_cnt = word_cnt61_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_0_ce0_local = 1'b1;
    end else begin
        mat_A_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd0) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_0_we0_local = 1'b1;
    end else begin
        mat_A_0_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_1_ce0_local = 1'b1;
    end else begin
        mat_A_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd1) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_1_we0_local = 1'b1;
    end else begin
        mat_A_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_2_ce0_local = 1'b1;
    end else begin
        mat_A_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd2) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_2_we0_local = 1'b1;
    end else begin
        mat_A_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_3_ce0_local = 1'b1;
    end else begin
        mat_A_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd3) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_3_we0_local = 1'b1;
    end else begin
        mat_A_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_4_ce0_local = 1'b1;
    end else begin
        mat_A_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd4) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_4_we0_local = 1'b1;
    end else begin
        mat_A_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_5_ce0_local = 1'b1;
    end else begin
        mat_A_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd5) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_5_we0_local = 1'b1;
    end else begin
        mat_A_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_6_ce0_local = 1'b1;
    end else begin
        mat_A_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd6) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_6_we0_local = 1'b1;
    end else begin
        mat_A_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        mat_A_7_ce0_local = 1'b1;
    end else begin
        mat_A_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (trunc_ln50_fu_264_p1 == 3'd7) & (1'b1 == ap_CS_fsm_state1) & (tmp_fu_302_p3 == 1'd0))) begin
        mat_A_7_we0_local = 1'b1;
    end else begin
        mat_A_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign S_AXIS_TREADY = regslice_both_S_AXIS_V_data_V_U_ack_in;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | (1'b0 == S_AXIS_TVALID_int_regslice) | (ap_done_reg == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln50_fu_392_p2 = ((ap_sig_allocacmp_word_cnt == 10'd519) ? 1'b1 : 1'b0);

assign lshr_ln_fu_268_p4 = {{ap_sig_allocacmp_word_cnt[8:3]}};

assign mat_A_0_address0 = zext_ln54_fu_278_p1;

assign mat_A_0_ce0 = mat_A_0_ce0_local;

assign mat_A_0_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_0_we0 = mat_A_0_we0_local;

assign mat_A_1_address0 = zext_ln54_fu_278_p1;

assign mat_A_1_ce0 = mat_A_1_ce0_local;

assign mat_A_1_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_1_we0 = mat_A_1_we0_local;

assign mat_A_2_address0 = zext_ln54_fu_278_p1;

assign mat_A_2_ce0 = mat_A_2_ce0_local;

assign mat_A_2_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_2_we0 = mat_A_2_we0_local;

assign mat_A_3_address0 = zext_ln54_fu_278_p1;

assign mat_A_3_ce0 = mat_A_3_ce0_local;

assign mat_A_3_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_3_we0 = mat_A_3_we0_local;

assign mat_A_4_address0 = zext_ln54_fu_278_p1;

assign mat_A_4_ce0 = mat_A_4_ce0_local;

assign mat_A_4_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_4_we0 = mat_A_4_we0_local;

assign mat_A_5_address0 = zext_ln54_fu_278_p1;

assign mat_A_5_ce0 = mat_A_5_ce0_local;

assign mat_A_5_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_5_we0 = mat_A_5_we0_local;

assign mat_A_6_address0 = zext_ln54_fu_278_p1;

assign mat_A_6_ce0 = mat_A_6_ce0_local;

assign mat_A_6_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_6_we0 = mat_A_6_we0_local;

assign mat_A_7_address0 = zext_ln54_fu_278_p1;

assign mat_A_7_ce0 = mat_A_7_ce0_local;

assign mat_A_7_d0 = S_AXIS_TDATA_int_regslice;

assign mat_A_7_we0 = mat_A_7_we0_local;

assign tmp_fu_302_p3 = ap_sig_allocacmp_word_cnt[32'd9];

assign trunc_ln50_fu_264_p1 = ap_sig_allocacmp_word_cnt[2:0];

assign word_cnt_5_fu_310_p2 = (ap_sig_allocacmp_word_cnt + 10'd1);

assign word_cnt_load_fu_261_p1 = ap_sig_allocacmp_word_cnt;

assign zext_ln54_fu_278_p1 = lshr_ln_fu_268_p4;

endmodule //myip_v2_0_HLS_Loop_myip_v2_0_HLS_read_inputs_proc
