-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myip_v1_0_HLS is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    S_AXIS_TVALID : IN STD_LOGIC;
    S_AXIS_TREADY : OUT STD_LOGIC;
    S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    M_AXIS_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    M_AXIS_TVALID : OUT STD_LOGIC;
    M_AXIS_TREADY : IN STD_LOGIC;
    M_AXIS_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    M_AXIS_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    M_AXIS_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of myip_v1_0_HLS is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myip_v1_0_HLS_myip_v1_0_HLS,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.135000,HLS_SYN_LAT=662,HLS_SYN_TPT=none,HLS_SYN_MEM=9,HLS_SYN_DSP=0,HLS_SYN_FF=402,HLS_SYN_LUT=964,HLS_VERSION=2025_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";

    signal ap_rst_n_inv : STD_LOGIC;
    signal mat_A_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mat_A_ce0 : STD_LOGIC;
    signal mat_A_we0 : STD_LOGIC;
    signal mat_A_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_A_ce1 : STD_LOGIC;
    signal mat_A_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_A_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mat_A_1_ce0 : STD_LOGIC;
    signal mat_A_1_we0 : STD_LOGIC;
    signal mat_A_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_A_1_ce1 : STD_LOGIC;
    signal mat_A_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_A_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mat_A_2_ce0 : STD_LOGIC;
    signal mat_A_2_we0 : STD_LOGIC;
    signal mat_A_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_A_2_ce1 : STD_LOGIC;
    signal mat_A_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_A_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal mat_A_3_ce0 : STD_LOGIC;
    signal mat_A_3_we0 : STD_LOGIC;
    signal mat_A_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_A_3_ce1 : STD_LOGIC;
    signal mat_A_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal mat_RES_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal mat_RES_ce0 : STD_LOGIC;
    signal mat_RES_we0 : STD_LOGIC;
    signal mat_RES_q0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_idle : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_ready : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_we0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_we0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_we0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_we0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_S_AXIS_TREADY : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out_ap_vld : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_idle : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_ready : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce1 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce1 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce1 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce1 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_we0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_d0 : STD_LOGIC_VECTOR (23 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_idle : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_ready : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TREADY : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_ce0 : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID : STD_LOGIC;
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal M_AXIS_TDATA_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal M_AXIS_TKEEP_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal M_AXIS_TSTRB_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal M_AXIS_TLAST_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal regslice_both_M_AXIS_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal regslice_both_S_AXIS_V_data_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal S_AXIS_TVALID_int_regslice : STD_LOGIC;
    signal S_AXIS_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_S_AXIS_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_S_AXIS_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_apdone_blk : STD_LOGIC;
    signal S_AXIS_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_S_AXIS_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_S_AXIS_V_last_V_U_ack_in : STD_LOGIC;
    signal M_AXIS_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal M_AXIS_TVALID_int_regslice : STD_LOGIC;
    signal M_AXIS_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_M_AXIS_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal M_AXIS_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal M_AXIS_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_apdone_blk : STD_LOGIC;
    signal M_AXIS_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_M_AXIS_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_M_AXIS_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        S_AXIS_TVALID : IN STD_LOGIC;
        mat_A_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_ce0 : OUT STD_LOGIC;
        mat_A_we0 : OUT STD_LOGIC;
        mat_A_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_A_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_1_ce0 : OUT STD_LOGIC;
        mat_A_1_we0 : OUT STD_LOGIC;
        mat_A_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_A_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_2_ce0 : OUT STD_LOGIC;
        mat_A_2_we0 : OUT STD_LOGIC;
        mat_A_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_A_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_3_ce0 : OUT STD_LOGIC;
        mat_A_3_we0 : OUT STD_LOGIC;
        mat_A_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        S_AXIS_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        S_AXIS_TREADY : OUT STD_LOGIC;
        S_AXIS_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        S_AXIS_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        mat_B_7_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_7_out_ap_vld : OUT STD_LOGIC;
        mat_B_6_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_6_out_ap_vld : OUT STD_LOGIC;
        mat_B_5_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_5_out_ap_vld : OUT STD_LOGIC;
        mat_B_4_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_4_out_ap_vld : OUT STD_LOGIC;
        mat_B_3_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_3_out_ap_vld : OUT STD_LOGIC;
        mat_B_2_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_2_out_ap_vld : OUT STD_LOGIC;
        mat_B_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_1_out_ap_vld : OUT STD_LOGIC;
        mat_B_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        mat_B_out_ap_vld : OUT STD_LOGIC );
    end component;


    component myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        mat_A_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_ce0 : OUT STD_LOGIC;
        mat_A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_A_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_ce1 : OUT STD_LOGIC;
        mat_A_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_A_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_1_ce0 : OUT STD_LOGIC;
        mat_A_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_A_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_1_ce1 : OUT STD_LOGIC;
        mat_A_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_A_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_2_ce0 : OUT STD_LOGIC;
        mat_A_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_A_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_2_ce1 : OUT STD_LOGIC;
        mat_A_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_A_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_3_ce0 : OUT STD_LOGIC;
        mat_A_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_A_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        mat_A_3_ce1 : OUT STD_LOGIC;
        mat_A_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_1_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_2_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_3_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_4_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_5_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_6_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_B_7_reload : IN STD_LOGIC_VECTOR (31 downto 0);
        mat_RES_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        mat_RES_ce0 : OUT STD_LOGIC;
        mat_RES_we0 : OUT STD_LOGIC;
        mat_RES_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        M_AXIS_TREADY : IN STD_LOGIC;
        mat_RES_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        mat_RES_ce0 : OUT STD_LOGIC;
        mat_RES_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
        M_AXIS_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        M_AXIS_TVALID : OUT STD_LOGIC;
        M_AXIS_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        M_AXIS_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        M_AXIS_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component myip_v1_0_HLS_mat_RES_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (23 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
    end component;


    component myip_v1_0_HLS_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    mat_A_U : component myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => mat_A_address0,
        ce0 => mat_A_ce0,
        we0 => mat_A_we0,
        d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_d0,
        q0 => mat_A_q0,
        address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address1,
        ce1 => mat_A_ce1,
        q1 => mat_A_q1);

    mat_A_1_U : component myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => mat_A_1_address0,
        ce0 => mat_A_1_ce0,
        we0 => mat_A_1_we0,
        d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_d0,
        q0 => mat_A_1_q0,
        address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address1,
        ce1 => mat_A_1_ce1,
        q1 => mat_A_1_q1);

    mat_A_2_U : component myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => mat_A_2_address0,
        ce0 => mat_A_2_ce0,
        we0 => mat_A_2_we0,
        d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_d0,
        q0 => mat_A_2_q0,
        address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address1,
        ce1 => mat_A_2_ce1,
        q1 => mat_A_2_q1);

    mat_A_3_U : component myip_v1_0_HLS_mat_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 128,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => mat_A_3_address0,
        ce0 => mat_A_3_ce0,
        we0 => mat_A_3_we0,
        d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_d0,
        q0 => mat_A_3_q0,
        address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address1,
        ce1 => mat_A_3_ce1,
        q1 => mat_A_3_q1);

    mat_RES_U : component myip_v1_0_HLS_mat_RES_RAM_AUTO_1R1W
    generic map (
        DataWidth => 24,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => mat_RES_address0,
        ce0 => mat_RES_ce0,
        we0 => mat_RES_we0,
        d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_d0,
        q0 => mat_RES_q0);

    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106 : component myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start,
        ap_done => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done,
        ap_idle => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_idle,
        ap_ready => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_ready,
        S_AXIS_TVALID => S_AXIS_TVALID_int_regslice,
        mat_A_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_address0,
        mat_A_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_ce0,
        mat_A_we0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_we0,
        mat_A_d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_d0,
        mat_A_1_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_address0,
        mat_A_1_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_ce0,
        mat_A_1_we0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_we0,
        mat_A_1_d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_d0,
        mat_A_2_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_address0,
        mat_A_2_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_ce0,
        mat_A_2_we0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_we0,
        mat_A_2_d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_d0,
        mat_A_3_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_address0,
        mat_A_3_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_ce0,
        mat_A_3_we0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_we0,
        mat_A_3_d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_d0,
        S_AXIS_TDATA => S_AXIS_TDATA_int_regslice,
        S_AXIS_TREADY => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_S_AXIS_TREADY,
        S_AXIS_TKEEP => S_AXIS_TKEEP_int_regslice,
        S_AXIS_TSTRB => S_AXIS_TSTRB_int_regslice,
        S_AXIS_TLAST => S_AXIS_TLAST_int_regslice,
        mat_B_7_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out,
        mat_B_7_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out_ap_vld,
        mat_B_6_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out,
        mat_B_6_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out_ap_vld,
        mat_B_5_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out,
        mat_B_5_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out_ap_vld,
        mat_B_4_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out,
        mat_B_4_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out_ap_vld,
        mat_B_3_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out,
        mat_B_3_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out_ap_vld,
        mat_B_2_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out,
        mat_B_2_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out_ap_vld,
        mat_B_1_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out,
        mat_B_1_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out_ap_vld,
        mat_B_out => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out,
        mat_B_out_ap_vld => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out_ap_vld);

    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130 : component myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start,
        ap_done => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done,
        ap_idle => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_idle,
        ap_ready => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_ready,
        mat_A_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address0,
        mat_A_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce0,
        mat_A_q0 => mat_A_q0,
        mat_A_address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address1,
        mat_A_ce1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce1,
        mat_A_q1 => mat_A_q1,
        mat_A_1_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address0,
        mat_A_1_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce0,
        mat_A_1_q0 => mat_A_1_q0,
        mat_A_1_address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address1,
        mat_A_1_ce1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce1,
        mat_A_1_q1 => mat_A_1_q1,
        mat_A_2_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address0,
        mat_A_2_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce0,
        mat_A_2_q0 => mat_A_2_q0,
        mat_A_2_address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address1,
        mat_A_2_ce1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce1,
        mat_A_2_q1 => mat_A_2_q1,
        mat_A_3_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address0,
        mat_A_3_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce0,
        mat_A_3_q0 => mat_A_3_q0,
        mat_A_3_address1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address1,
        mat_A_3_ce1 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce1,
        mat_A_3_q1 => mat_A_3_q1,
        mat_B_1_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_1_out,
        mat_B_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_out,
        mat_B_2_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_2_out,
        mat_B_3_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_3_out,
        mat_B_4_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_4_out,
        mat_B_5_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_5_out,
        mat_B_6_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_6_out,
        mat_B_7_reload => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_B_7_out,
        mat_RES_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_address0,
        mat_RES_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_ce0,
        mat_RES_we0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_we0,
        mat_RES_d0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_d0);

    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147 : component myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start,
        ap_done => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done,
        ap_idle => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_idle,
        ap_ready => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_ready,
        M_AXIS_TREADY => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TREADY,
        mat_RES_address0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_address0,
        mat_RES_ce0 => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_ce0,
        mat_RES_q0 => mat_RES_q0,
        M_AXIS_TDATA => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA,
        M_AXIS_TVALID => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID,
        M_AXIS_TKEEP => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP,
        M_AXIS_TSTRB => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB,
        M_AXIS_TLAST => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST);

    regslice_both_S_AXIS_V_data_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TDATA,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_data_V_U_ack_in,
        data_out => S_AXIS_TDATA_int_regslice,
        vld_out => S_AXIS_TVALID_int_regslice,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_data_V_U_apdone_blk);

    regslice_both_S_AXIS_V_keep_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TKEEP,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_keep_V_U_ack_in,
        data_out => S_AXIS_TKEEP_int_regslice,
        vld_out => regslice_both_S_AXIS_V_keep_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_keep_V_U_apdone_blk);

    regslice_both_S_AXIS_V_strb_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TSTRB,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_strb_V_U_ack_in,
        data_out => S_AXIS_TSTRB_int_regslice,
        vld_out => regslice_both_S_AXIS_V_strb_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_strb_V_U_apdone_blk);

    regslice_both_S_AXIS_V_last_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => S_AXIS_TLAST,
        vld_in => S_AXIS_TVALID,
        ack_in => regslice_both_S_AXIS_V_last_V_U_ack_in,
        data_out => S_AXIS_TLAST_int_regslice,
        vld_out => regslice_both_S_AXIS_V_last_V_U_vld_out,
        ack_out => S_AXIS_TREADY_int_regslice,
        apdone_blk => regslice_both_S_AXIS_V_last_V_U_apdone_blk);

    regslice_both_M_AXIS_V_data_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => M_AXIS_TDATA_int_regslice,
        vld_in => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID,
        ack_in => M_AXIS_TREADY_int_regslice,
        data_out => M_AXIS_TDATA,
        vld_out => regslice_both_M_AXIS_V_data_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_data_V_U_apdone_blk);

    regslice_both_M_AXIS_V_keep_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => M_AXIS_TKEEP_int_regslice,
        vld_in => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID,
        ack_in => regslice_both_M_AXIS_V_keep_V_U_ack_in_dummy,
        data_out => M_AXIS_TKEEP,
        vld_out => regslice_both_M_AXIS_V_keep_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_keep_V_U_apdone_blk);

    regslice_both_M_AXIS_V_strb_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => M_AXIS_TSTRB_int_regslice,
        vld_in => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID,
        ack_in => regslice_both_M_AXIS_V_strb_V_U_ack_in_dummy,
        data_out => M_AXIS_TSTRB,
        vld_out => regslice_both_M_AXIS_V_strb_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_strb_V_U_apdone_blk);

    regslice_both_M_AXIS_V_last_V_U : component myip_v1_0_HLS_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => M_AXIS_TLAST_int_regslice,
        vld_in => grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID,
        ack_in => regslice_both_M_AXIS_V_last_V_U_ack_in_dummy,
        data_out => M_AXIS_TLAST,
        vld_out => regslice_both_M_AXIS_V_last_V_U_vld_out,
        ack_out => M_AXIS_TREADY,
        apdone_blk => regslice_both_M_AXIS_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_ready = ap_const_logic_1)) then 
                    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_ready = ap_const_logic_1)) then 
                    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_ready = ap_const_logic_1)) then 
                    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID = ap_const_logic_1))) then
                M_AXIS_TDATA_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA;
                M_AXIS_TKEEP_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP;
                M_AXIS_TLAST_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST;
                M_AXIS_TSTRB_reg <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done, ap_CS_fsm, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, regslice_both_M_AXIS_V_data_V_U_apdone_blk, ap_CS_fsm_state8)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state5) and (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if (((regslice_both_M_AXIS_V_data_V_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;

    M_AXIS_TDATA_int_regslice_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID, ap_CS_fsm_state7, M_AXIS_TDATA_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID = ap_const_logic_1))) then 
            M_AXIS_TDATA_int_regslice <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TDATA;
        else 
            M_AXIS_TDATA_int_regslice <= M_AXIS_TDATA_reg;
        end if; 
    end process;


    M_AXIS_TKEEP_int_regslice_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP, ap_CS_fsm_state7, M_AXIS_TKEEP_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID = ap_const_logic_1))) then 
            M_AXIS_TKEEP_int_regslice <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TKEEP;
        else 
            M_AXIS_TKEEP_int_regslice <= M_AXIS_TKEEP_reg;
        end if; 
    end process;


    M_AXIS_TLAST_int_regslice_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST, ap_CS_fsm_state7, M_AXIS_TLAST_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID = ap_const_logic_1))) then 
            M_AXIS_TLAST_int_regslice <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TLAST;
        else 
            M_AXIS_TLAST_int_regslice <= M_AXIS_TLAST_reg;
        end if; 
    end process;


    M_AXIS_TSTRB_int_regslice_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB, ap_CS_fsm_state7, M_AXIS_TSTRB_reg)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID = ap_const_logic_1))) then 
            M_AXIS_TSTRB_int_regslice <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TSTRB;
        else 
            M_AXIS_TSTRB_int_regslice <= M_AXIS_TSTRB_reg;
        end if; 
    end process;

    M_AXIS_TVALID <= regslice_both_M_AXIS_V_data_V_U_vld_out;
    M_AXIS_TVALID_int_regslice <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TVALID;
    S_AXIS_TREADY <= regslice_both_S_AXIS_V_data_V_U_ack_in;

    S_AXIS_TREADY_int_regslice_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_S_AXIS_TREADY, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            S_AXIS_TREADY_int_regslice <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_S_AXIS_TREADY;
        else 
            S_AXIS_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done)
    begin
        if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done)
    begin
        if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done)
    begin
        if ((grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(regslice_both_M_AXIS_V_data_V_U_apdone_blk)
    begin
        if ((regslice_both_M_AXIS_V_data_V_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_ap_start_reg;
    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_ap_start_reg;
    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_M_AXIS_TREADY <= (ap_CS_fsm_state7 and M_AXIS_TREADY_int_regslice);
    grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_ap_start_reg;

    mat_A_1_address0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_address0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_1_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_1_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_address0;
        else 
            mat_A_1_address0 <= "XXXXXXX";
        end if; 
    end process;


    mat_A_1_ce0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_ce0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_1_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_1_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_ce0;
        else 
            mat_A_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_1_ce1_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_1_ce1 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_1_ce1;
        else 
            mat_A_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_1_we0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_1_we0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_1_we0;
        else 
            mat_A_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_2_address0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_address0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_2_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_2_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_address0;
        else 
            mat_A_2_address0 <= "XXXXXXX";
        end if; 
    end process;


    mat_A_2_ce0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_ce0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_2_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_2_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_ce0;
        else 
            mat_A_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_2_ce1_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_2_ce1 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_2_ce1;
        else 
            mat_A_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_2_we0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_2_we0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_2_we0;
        else 
            mat_A_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_3_address0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_address0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_3_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_3_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_address0;
        else 
            mat_A_3_address0 <= "XXXXXXX";
        end if; 
    end process;


    mat_A_3_ce0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_ce0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_3_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_3_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_ce0;
        else 
            mat_A_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_3_ce1_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_3_ce1 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_3_ce1;
        else 
            mat_A_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_3_we0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_3_we0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_3_we0;
        else 
            mat_A_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_address0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_address0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_address0;
        else 
            mat_A_address0 <= "XXXXXXX";
        end if; 
    end process;


    mat_A_ce0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_ce0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce0, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_ce0;
        else 
            mat_A_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_ce1_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce1, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_A_ce1 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_A_ce1;
        else 
            mat_A_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    mat_A_we0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            mat_A_we0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs_fu_106_mat_A_we0;
        else 
            mat_A_we0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_RES_address0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_address0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            mat_RES_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_RES_address0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_address0;
        else 
            mat_RES_address0 <= "XXXXXX";
        end if; 
    end process;


    mat_RES_ce0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_ce0, grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            mat_RES_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_write_outputs_fu_147_mat_RES_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_RES_ce0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_ce0;
        else 
            mat_RES_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    mat_RES_we0_assign_proc : process(grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            mat_RES_we0 <= grp_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute_fu_130_mat_RES_we0;
        else 
            mat_RES_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
