// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        mat_A_address0,
        mat_A_ce0,
        mat_A_q0,
        mat_A_address1,
        mat_A_ce1,
        mat_A_q1,
        mat_A_1_address0,
        mat_A_1_ce0,
        mat_A_1_q0,
        mat_A_1_address1,
        mat_A_1_ce1,
        mat_A_1_q1,
        mat_A_2_address0,
        mat_A_2_ce0,
        mat_A_2_q0,
        mat_A_2_address1,
        mat_A_2_ce1,
        mat_A_2_q1,
        mat_A_3_address0,
        mat_A_3_ce0,
        mat_A_3_q0,
        mat_A_3_address1,
        mat_A_3_ce1,
        mat_A_3_q1,
        mat_B_1_reload,
        mat_B_reload,
        mat_B_2_reload,
        mat_B_3_reload,
        mat_B_4_reload,
        mat_B_5_reload,
        mat_B_6_reload,
        mat_B_7_reload,
        mat_RES_address0,
        mat_RES_ce0,
        mat_RES_we0,
        mat_RES_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [6:0] mat_A_address0;
output   mat_A_ce0;
input  [31:0] mat_A_q0;
output  [6:0] mat_A_address1;
output   mat_A_ce1;
input  [31:0] mat_A_q1;
output  [6:0] mat_A_1_address0;
output   mat_A_1_ce0;
input  [31:0] mat_A_1_q0;
output  [6:0] mat_A_1_address1;
output   mat_A_1_ce1;
input  [31:0] mat_A_1_q1;
output  [6:0] mat_A_2_address0;
output   mat_A_2_ce0;
input  [31:0] mat_A_2_q0;
output  [6:0] mat_A_2_address1;
output   mat_A_2_ce1;
input  [31:0] mat_A_2_q1;
output  [6:0] mat_A_3_address0;
output   mat_A_3_ce0;
input  [31:0] mat_A_3_q0;
output  [6:0] mat_A_3_address1;
output   mat_A_3_ce1;
input  [31:0] mat_A_3_q1;
input  [31:0] mat_B_1_reload;
input  [31:0] mat_B_reload;
input  [31:0] mat_B_2_reload;
input  [31:0] mat_B_3_reload;
input  [31:0] mat_B_4_reload;
input  [31:0] mat_B_5_reload;
input  [31:0] mat_B_6_reload;
input  [31:0] mat_B_7_reload;
output  [5:0] mat_RES_address0;
output   mat_RES_ce0;
output   mat_RES_we0;
output  [23:0] mat_RES_d0;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln58_fu_277_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [6:0] i_1_reg_431;
reg   [6:0] i_1_reg_431_pp0_iter1_reg;
reg   [23:0] trunc_ln1_reg_480;
wire   [63:0] zext_ln63_fu_299_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln63_1_fu_315_p1;
wire   [63:0] zext_ln58_fu_380_p1;
reg   [6:0] i_fu_64;
wire   [6:0] i_2_fu_283_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_i_1;
reg    mat_A_ce1_local;
reg    mat_A_ce0_local;
reg    mat_A_1_ce1_local;
reg    mat_A_1_ce0_local;
reg    mat_A_2_ce1_local;
reg    mat_A_2_ce0_local;
reg    mat_A_3_ce1_local;
reg    mat_A_3_ce0_local;
reg    mat_RES_we0_local;
reg    mat_RES_ce0_local;
wire   [6:0] shl_ln63_fu_293_p2;
wire   [5:0] trunc_ln63_fu_289_p1;
wire   [6:0] or_ln_fu_307_p3;
wire   [31:0] mul_ln62_fu_229_p2;
wire   [31:0] mul_ln62_1_fu_234_p2;
wire   [31:0] mul_ln62_2_fu_239_p2;
wire   [31:0] mul_ln62_3_fu_244_p2;
wire   [31:0] add_ln62_1_fu_334_p2;
wire   [31:0] add_ln62_fu_328_p2;
wire   [31:0] mul_ln62_4_fu_249_p2;
wire   [31:0] mul_ln62_5_fu_254_p2;
wire   [31:0] mul_ln62_6_fu_259_p2;
wire   [31:0] mul_ln62_7_fu_264_p2;
wire   [31:0] add_ln62_4_fu_352_p2;
wire   [31:0] add_ln62_3_fu_346_p2;
wire   [31:0] add_ln62_5_fu_358_p2;
wire   [31:0] add_ln62_2_fu_340_p2;
wire   [31:0] temp_fu_364_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i_fu_64 = 7'd0;
#0 ap_done_reg = 1'b0;
end

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U17(
    .din0(mat_A_1_q1),
    .din1(mat_B_1_reload),
    .dout(mul_ln62_fu_229_p2)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U18(
    .din0(mat_A_q1),
    .din1(mat_B_reload),
    .dout(mul_ln62_1_fu_234_p2)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U19(
    .din0(mat_A_2_q1),
    .din1(mat_B_2_reload),
    .dout(mul_ln62_2_fu_239_p2)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U20(
    .din0(mat_A_3_q1),
    .din1(mat_B_3_reload),
    .dout(mul_ln62_3_fu_244_p2)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U21(
    .din0(mat_A_q0),
    .din1(mat_B_4_reload),
    .dout(mul_ln62_4_fu_249_p2)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U22(
    .din0(mat_A_1_q0),
    .din1(mat_B_5_reload),
    .dout(mul_ln62_5_fu_254_p2)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U23(
    .din0(mat_A_2_q0),
    .din1(mat_B_6_reload),
    .dout(mul_ln62_6_fu_259_p2)
);

myip_v1_0_HLS_mul_32s_32s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mul_32s_32s_32_1_1_U24(
    .din0(mat_A_3_q0),
    .din1(mat_B_7_reload),
    .dout(mul_ln62_7_fu_264_p2)
);

myip_v1_0_HLS_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln58_fu_277_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_64 <= i_2_fu_283_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        i_1_reg_431 <= ap_sig_allocacmp_i_1;
        i_1_reg_431_pp0_iter1_reg <= i_1_reg_431;
        trunc_ln1_reg_480 <= {{temp_fu_364_p2[31:8]}};
    end
end

always @ (*) begin
    if (((icmp_ln58_fu_277_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 7'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_1_ce0_local = 1'b1;
    end else begin
        mat_A_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_1_ce1_local = 1'b1;
    end else begin
        mat_A_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_2_ce0_local = 1'b1;
    end else begin
        mat_A_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_2_ce1_local = 1'b1;
    end else begin
        mat_A_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_3_ce0_local = 1'b1;
    end else begin
        mat_A_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_3_ce1_local = 1'b1;
    end else begin
        mat_A_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_ce0_local = 1'b1;
    end else begin
        mat_A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_ce1_local = 1'b1;
    end else begin
        mat_A_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mat_RES_ce0_local = 1'b1;
    end else begin
        mat_RES_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        mat_RES_we0_local = 1'b1;
    end else begin
        mat_RES_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln62_1_fu_334_p2 = (mul_ln62_2_fu_239_p2 + mul_ln62_3_fu_244_p2);

assign add_ln62_2_fu_340_p2 = (add_ln62_1_fu_334_p2 + add_ln62_fu_328_p2);

assign add_ln62_3_fu_346_p2 = (mul_ln62_4_fu_249_p2 + mul_ln62_5_fu_254_p2);

assign add_ln62_4_fu_352_p2 = (mul_ln62_6_fu_259_p2 + mul_ln62_7_fu_264_p2);

assign add_ln62_5_fu_358_p2 = (add_ln62_4_fu_352_p2 + add_ln62_3_fu_346_p2);

assign add_ln62_fu_328_p2 = (mul_ln62_fu_229_p2 + mul_ln62_1_fu_234_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign i_2_fu_283_p2 = (ap_sig_allocacmp_i_1 + 7'd1);

assign icmp_ln58_fu_277_p2 = ((ap_sig_allocacmp_i_1 == 7'd64) ? 1'b1 : 1'b0);

assign mat_A_1_address0 = zext_ln63_1_fu_315_p1;

assign mat_A_1_address1 = zext_ln63_fu_299_p1;

assign mat_A_1_ce0 = mat_A_1_ce0_local;

assign mat_A_1_ce1 = mat_A_1_ce1_local;

assign mat_A_2_address0 = zext_ln63_1_fu_315_p1;

assign mat_A_2_address1 = zext_ln63_fu_299_p1;

assign mat_A_2_ce0 = mat_A_2_ce0_local;

assign mat_A_2_ce1 = mat_A_2_ce1_local;

assign mat_A_3_address0 = zext_ln63_1_fu_315_p1;

assign mat_A_3_address1 = zext_ln63_fu_299_p1;

assign mat_A_3_ce0 = mat_A_3_ce0_local;

assign mat_A_3_ce1 = mat_A_3_ce1_local;

assign mat_A_address0 = zext_ln63_1_fu_315_p1;

assign mat_A_address1 = zext_ln63_fu_299_p1;

assign mat_A_ce0 = mat_A_ce0_local;

assign mat_A_ce1 = mat_A_ce1_local;

assign mat_RES_address0 = zext_ln58_fu_380_p1;

assign mat_RES_ce0 = mat_RES_ce0_local;

assign mat_RES_d0 = trunc_ln1_reg_480;

assign mat_RES_we0 = mat_RES_we0_local;

assign or_ln_fu_307_p3 = {{trunc_ln63_fu_289_p1}, {1'd1}};

assign shl_ln63_fu_293_p2 = ap_sig_allocacmp_i_1 << 7'd1;

assign temp_fu_364_p2 = (add_ln62_5_fu_358_p2 + add_ln62_2_fu_340_p2);

assign trunc_ln63_fu_289_p1 = ap_sig_allocacmp_i_1[5:0];

assign zext_ln58_fu_380_p1 = i_1_reg_431_pp0_iter1_reg;

assign zext_ln63_1_fu_315_p1 = or_ln_fu_307_p3;

assign zext_ln63_fu_299_p1 = shl_ln63_fu_293_p2;

endmodule //myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_compute
