// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        S_AXIS_TVALID,
        mat_A_address0,
        mat_A_ce0,
        mat_A_we0,
        mat_A_d0,
        mat_A_1_address0,
        mat_A_1_ce0,
        mat_A_1_we0,
        mat_A_1_d0,
        mat_A_2_address0,
        mat_A_2_ce0,
        mat_A_2_we0,
        mat_A_2_d0,
        mat_A_3_address0,
        mat_A_3_ce0,
        mat_A_3_we0,
        mat_A_3_d0,
        S_AXIS_TDATA,
        S_AXIS_TREADY,
        S_AXIS_TKEEP,
        S_AXIS_TSTRB,
        S_AXIS_TLAST,
        mat_B_7_out,
        mat_B_7_out_ap_vld,
        mat_B_6_out,
        mat_B_6_out_ap_vld,
        mat_B_5_out,
        mat_B_5_out_ap_vld,
        mat_B_4_out,
        mat_B_4_out_ap_vld,
        mat_B_3_out,
        mat_B_3_out_ap_vld,
        mat_B_2_out,
        mat_B_2_out_ap_vld,
        mat_B_1_out,
        mat_B_1_out_ap_vld,
        mat_B_out,
        mat_B_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   S_AXIS_TVALID;
output  [6:0] mat_A_address0;
output   mat_A_ce0;
output   mat_A_we0;
output  [31:0] mat_A_d0;
output  [6:0] mat_A_1_address0;
output   mat_A_1_ce0;
output   mat_A_1_we0;
output  [31:0] mat_A_1_d0;
output  [6:0] mat_A_2_address0;
output   mat_A_2_ce0;
output   mat_A_2_we0;
output  [31:0] mat_A_2_d0;
output  [6:0] mat_A_3_address0;
output   mat_A_3_ce0;
output   mat_A_3_we0;
output  [31:0] mat_A_3_d0;
input  [31:0] S_AXIS_TDATA;
output   S_AXIS_TREADY;
input  [3:0] S_AXIS_TKEEP;
input  [3:0] S_AXIS_TSTRB;
input  [0:0] S_AXIS_TLAST;
output  [31:0] mat_B_7_out;
output   mat_B_7_out_ap_vld;
output  [31:0] mat_B_6_out;
output   mat_B_6_out_ap_vld;
output  [31:0] mat_B_5_out;
output   mat_B_5_out_ap_vld;
output  [31:0] mat_B_4_out;
output   mat_B_4_out_ap_vld;
output  [31:0] mat_B_3_out;
output   mat_B_3_out_ap_vld;
output  [31:0] mat_B_2_out;
output   mat_B_2_out_ap_vld;
output  [31:0] mat_B_1_out;
output   mat_B_1_out_ap_vld;
output  [31:0] mat_B_out;
output   mat_B_out_ap_vld;

reg ap_idle;
reg S_AXIS_TREADY;
reg mat_B_7_out_ap_vld;
reg mat_B_6_out_ap_vld;
reg mat_B_5_out_ap_vld;
reg mat_B_4_out_ap_vld;
reg mat_B_3_out_ap_vld;
reg mat_B_2_out_ap_vld;
reg mat_B_1_out_ap_vld;
reg mat_B_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln47_fu_268_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    S_AXIS_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg   [9:0] word_cnt_2_reg_477;
reg    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln47_fu_280_p1;
reg   [1:0] trunc_ln47_reg_484;
reg   [6:0] lshr_ln_reg_488;
reg   [0:0] tmp_reg_493;
wire   [63:0] zext_ln38_fu_335_p1;
reg   [9:0] word_cnt_fu_104;
wire   [9:0] add_ln47_fu_274_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_word_cnt_2;
wire    ap_block_pp0_stage0;
reg   [31:0] mat_B_fu_108;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [31:0] mat_B_1_fu_112;
reg   [31:0] mat_B_2_fu_116;
reg   [31:0] mat_B_3_fu_120;
reg   [31:0] mat_B_4_fu_124;
reg   [31:0] mat_B_5_fu_128;
reg   [31:0] mat_B_6_fu_132;
reg   [31:0] mat_B_7_fu_136;
reg    ap_block_pp0_stage0_01001_grp1;
reg    mat_A_2_we0_local;
reg    mat_A_2_ce0_local;
reg    mat_A_1_we0_local;
reg    mat_A_1_ce0_local;
reg    mat_A_we0_local;
reg    mat_A_ce0_local;
reg    mat_A_3_we0_local;
reg    mat_A_3_ce0_local;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 word_cnt_fu_104 = 10'd0;
#0 mat_B_fu_108 = 32'd0;
#0 mat_B_1_fu_112 = 32'd0;
#0 mat_B_2_fu_116 = 32'd0;
#0 mat_B_3_fu_120 = 32'd0;
#0 mat_B_4_fu_124 = 32'd0;
#0 mat_B_5_fu_128 = 32'd0;
#0 mat_B_6_fu_132 = 32'd0;
#0 mat_B_7_fu_136 = 32'd0;
#0 ap_done_reg = 1'b0;
end

myip_v1_0_HLS_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln47_fu_268_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            word_cnt_fu_104 <= add_ln47_fu_274_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            word_cnt_fu_104 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_488 <= {{ap_sig_allocacmp_word_cnt_2[8:2]}};
        tmp_reg_493 <= ap_sig_allocacmp_word_cnt_2[32'd9];
        trunc_ln47_reg_484 <= trunc_ln47_fu_280_p1;
        word_cnt_2_reg_477 <= ap_sig_allocacmp_word_cnt_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1) & (word_cnt_2_reg_477 == 10'd513))) begin
        mat_B_1_fu_112 <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1) & (word_cnt_2_reg_477 == 10'd514))) begin
        mat_B_2_fu_116 <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1) & (word_cnt_2_reg_477 == 10'd515))) begin
        mat_B_3_fu_120 <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1) & (word_cnt_2_reg_477 == 10'd516))) begin
        mat_B_4_fu_124 <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1) & (word_cnt_2_reg_477 == 10'd517))) begin
        mat_B_5_fu_128 <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1) & (word_cnt_2_reg_477 == 10'd518))) begin
        mat_B_6_fu_132 <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1) & (word_cnt_2_reg_477 == 10'd519))) begin
        mat_B_7_fu_136 <= S_AXIS_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((~(word_cnt_2_reg_477 == 10'd518) & ~(word_cnt_2_reg_477 == 10'd517) & ~(word_cnt_2_reg_477 == 10'd516) & ~(word_cnt_2_reg_477 == 10'd515) & ~(word_cnt_2_reg_477 == 10'd514) & ~(word_cnt_2_reg_477 == 10'd513) & ~(word_cnt_2_reg_477 == 10'd519) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd1))) begin
        mat_B_fu_108 <= S_AXIS_TDATA;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_AXIS_TDATA_blk_n = S_AXIS_TVALID;
    end else begin
        S_AXIS_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        S_AXIS_TREADY = 1'b1;
    end else begin
        S_AXIS_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_word_cnt_2 = 10'd0;
    end else begin
        ap_sig_allocacmp_word_cnt_2 = word_cnt_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_1_ce0_local = 1'b1;
    end else begin
        mat_A_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd0) & (trunc_ln47_reg_484 == 2'd1))) begin
        mat_A_1_we0_local = 1'b1;
    end else begin
        mat_A_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_2_ce0_local = 1'b1;
    end else begin
        mat_A_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd0) & (trunc_ln47_reg_484 == 2'd2))) begin
        mat_A_2_we0_local = 1'b1;
    end else begin
        mat_A_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_3_ce0_local = 1'b1;
    end else begin
        mat_A_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd0) & (trunc_ln47_reg_484 == 2'd3))) begin
        mat_A_3_we0_local = 1'b1;
    end else begin
        mat_A_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_A_ce0_local = 1'b1;
    end else begin
        mat_A_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_reg_493 == 1'd0) & (trunc_ln47_reg_484 == 2'd0))) begin
        mat_A_we0_local = 1'b1;
    end else begin
        mat_A_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_1_out_ap_vld = 1'b1;
    end else begin
        mat_B_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_2_out_ap_vld = 1'b1;
    end else begin
        mat_B_2_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_3_out_ap_vld = 1'b1;
    end else begin
        mat_B_3_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_4_out_ap_vld = 1'b1;
    end else begin
        mat_B_4_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_5_out_ap_vld = 1'b1;
    end else begin
        mat_B_5_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_6_out_ap_vld = 1'b1;
    end else begin
        mat_B_6_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_7_out_ap_vld = 1'b1;
    end else begin
        mat_B_7_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln47_fu_268_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mat_B_out_ap_vld = 1'b1;
    end else begin
        mat_B_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln47_fu_274_p2 = (ap_sig_allocacmp_word_cnt_2 + 10'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((1'b0 == S_AXIS_TVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b0 == S_AXIS_TVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((1'b0 == S_AXIS_TVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == S_AXIS_TVALID) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln47_fu_268_p2 = ((ap_sig_allocacmp_word_cnt_2 == 10'd520) ? 1'b1 : 1'b0);

assign mat_A_1_address0 = zext_ln38_fu_335_p1;

assign mat_A_1_ce0 = mat_A_1_ce0_local;

assign mat_A_1_d0 = S_AXIS_TDATA;

assign mat_A_1_we0 = mat_A_1_we0_local;

assign mat_A_2_address0 = zext_ln38_fu_335_p1;

assign mat_A_2_ce0 = mat_A_2_ce0_local;

assign mat_A_2_d0 = S_AXIS_TDATA;

assign mat_A_2_we0 = mat_A_2_we0_local;

assign mat_A_3_address0 = zext_ln38_fu_335_p1;

assign mat_A_3_ce0 = mat_A_3_ce0_local;

assign mat_A_3_d0 = S_AXIS_TDATA;

assign mat_A_3_we0 = mat_A_3_we0_local;

assign mat_A_address0 = zext_ln38_fu_335_p1;

assign mat_A_ce0 = mat_A_ce0_local;

assign mat_A_d0 = S_AXIS_TDATA;

assign mat_A_we0 = mat_A_we0_local;

assign mat_B_1_out = mat_B_1_fu_112;

assign mat_B_2_out = mat_B_2_fu_116;

assign mat_B_3_out = mat_B_3_fu_120;

assign mat_B_4_out = mat_B_4_fu_124;

assign mat_B_5_out = mat_B_5_fu_128;

assign mat_B_6_out = mat_B_6_fu_132;

assign mat_B_7_out = mat_B_7_fu_136;

assign mat_B_out = mat_B_fu_108;

assign trunc_ln47_fu_280_p1 = ap_sig_allocacmp_word_cnt_2[1:0];

assign zext_ln38_fu_335_p1 = lshr_ln_reg_488;

endmodule //myip_v1_0_HLS_myip_v1_0_HLS_Pipeline_myip_v1_0_HLS_read_inputs
